### ISSUE TITLE
Create a guideline for how the 1:1 demonstration/user input sessions run

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#101]
### As a <user>

developer

### I would like to...

know how to carry out the demonstration sessions

### Because...

we want to make sure the process is transparent, uniform and involves a diverse range of the autistic community

### Acceptance criteria

- [x] Create a set of guidelines as a pull request
- [ ] get the guidelines reviewed

---

## Notes

* Associated pull request: 
* Current status:

---

## Updates

@KirstieJane pointed me to the following useful documents:
* [project-management/data-management.md](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/data-management.md)
* [project-management/participant-information-sheet.md](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/participant-information-sheet.md)
* [project-management/A6_ConsentForm.pdf](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/A6_ConsentForm.pdf)

**Comment by GeorgiaHCA** [comment]
Design questions for user testing sessions

**Comment by driscolle** [comment]
@GeorgiaHCA Hello, does Kirstie need to approve the 1-2-1 guidelines?  I wanted to put a status update on my tracker please?

**Comment by SaimaButt** [comment]
This issue has been complete as the documents have been reviewed. in issues #115 and #119
