### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#103]
**_We need wireframes before we start building prototypes_**

These are user journeys around the website - ideally they should be very clean to begin with, showing a basic structure without too much detail, content, or colour. They can be mapped out using pen and paper. 

- [x] Research and understand how to create wireframes
- [ ] Add any resources you find useful to the main GitHub repo to help others :)
- [x] Make sure the workflow and features of the wireframes meets the project's [business requirements](
https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/96/files?short_path=c9026eb#diff-c9026eb62eeb41fd822915481c2faadf)
- [ ] Investigate Open Human's backend/filemanagement system 
- [ ] Draw/make/write wireframe! 
- [ ] Upload it to the main Turing GitHub repo.

Here's a useful guide for making wireframes: 

https://simplysecure.org/blog/wireframing-intro 

The wireframe should be built using the backend filemanagement system provided by Open Humans:
https://github.com/OpenHumans/open-humans

I've made a folder where people can add their wireframes (as images if they're pen and paper), as well as a page to link to useful resources (currenlty still a pull request) 

https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/102

In March I'd love to host a workshop at The Turing to refine the wireframes, so it would be great to crack on with some versions to compare and refine. Feel free to comment on this pull request with any qs or get in touch by email (gaitkenhead@turing.com) or Gitter (https://gitter.im/alan-turing-institute/AutisticaCitizenScience). 

Thanks everyone!!

**Comment by GeorgiaHCA** [comment]
@MaxwellRiess and @JamesSCT thanks for agreeing to help! Looking forward to your insights. Any questions, comments, etc. please get in touch!

**Comment by MaxwellRiess** [comment]
Thanks @GeorgiaHCA! Very excited to get involved. 

One thing that strikes me is what devices we should be wire-framing for? Desktop, tablet and mobile? 

It's often good practice to design 'mobile first'. Because mobile devices are so much smaller, as it encourages you to focus on what is absolutely essential. 

But I don't know anything yet about your users! So please say if you think it's not appropriate.

**Comment by GeorgiaHCA** [comment]
Thanks for joining @MaxwellRiess ! Welcome. Very excited to have you on board. 🌟 

As many of our users will want to access the platform using their mobiles, I think that would be a great place to start so we can begin simply and iterate from there. The ideal is to design something which is useable on different devices, but a basic webpage is the MVP.

**Comment by fjThomasStanley** [comment]
Please see a prototype wireframe I have made for the platform. This wireframe has been developed during the Focus Group sessions hosted at Fujitsu:

Heroku Host:
https://fjautisticaexperiences.herokuapp.com

Source Code:
https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience

**Comment by fjThomasStanley** [comment]
We need to add a label to this issue indicating that this issue is a goal

**Comment by EllenDevereux** [comment]
Chris from Fujitsu has created wireframes and will be uploaded during/after his meeting with @GeorgiaHCA.

Georgia will meet with Ellen after that meeting to discuss changes to this issue so as to meet both teams requirements.
