### ISSUE TITLE
Organise a wireframing workshop

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#104]
We need to refine some versions of wireframes which we can test out with members of the community. 

- [x] Start working on initial wireframe designs in preparation 
- [x] Deecide on date and venue
- [x] Book room, refreshments etc. 
- [x] Invite collaborators - OH, and autistic community
- [x] Create agenda
- [ ] Upload notes of meeting to GitHub

**Comment by GeorgiaHCA** [comment]
We have a date: 27th March
It will be at the Fujitsu offices - thanks for booking ED :-D

**Comment by fjThomasStanley** [comment]
Chris Legg requests a 1hr slot in the 27th march meeting to present wireframes/run workshop

**Comment by EllenDevereux** [comment]
This has been done and minutes have been uploaded in a pull-request.

**Comment by EllenDevereux** [comment]
@GeorgiaHCA please link the pull request for these minutes/close this if the minutes have been merged already.
