### ISSUE TITLE
Open Humans and Fujitsu - building connections 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#105]
The Fujitsu team needs to understand the Open Humans data storage system in order to design wireframes, prototypes and build! 

@gedankenstuecke has agreed to meet the team and talk with them about the OH backend!
@SaimaButt - would you be able to organise a time that works for Bastian and your team?

**Comment by GeorgiaHCA** [comment]
Thank you both! 🌟 🌟

**Comment by gedankenstuecke** [comment]
Hey @SaimaButt and @GeorgiaHCA, let me know which days/times work well for you. E.g. I'm available most time slots on Monday & Tuesday next week.

**Comment by GeorgiaHCA** [comment]
Thanks @gedankenstuecke. Tuesday afternoon would work best for me! I'm free any time between 12 and 1? @SaimaButt it would be fab if Thomas and Ellen could join?

**Comment by KirstieJane** [comment]
I'm in Berkeley next week so I'm not available, and then I'm on strike for quite a lot of the following two weeks. So best to proceed without me if that's ok.

**Comment by GeorgiaHCA** [comment]
Totally understandable! Thanks for letting us know @KirstieJane. Hope all goes well

**Comment by fjThomasStanley** [comment]
I will be available from 13:00 today. @GeorgiaHCA and @gedankenstuecke what is the best method setting up a conference call, I can join on zoom or send out a Skype invite?

**Comment by GeorgiaHCA** [comment]
Hey, 

That's great! Thanks Thomas and Bastian. Would 3-4pm be a good time? Happy to Skype!

Best, 

Georgia

**Comment by gedankenstuecke** [comment]
Yep, 4-5 CET works for me today!
