### ISSUE TITLE
Onboard Lindsey 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#108]
Introduce Lindsey to the project 

- [x] Tour of the Turing
- [x] Tour of Repo & intro to project
- [x] Explain Stakeholder groups
- [x] Create GitHub account - first issue
- [x] First set of actions
- [x] Set up meeting between Lindsey and Ellen
- [x] Add permissions to repo

**Comment by lindsey-depledge** [comment]
Test comment

**Comment by GeorgiaHCA** [comment]
Yay! Well done :) Welcome to the repo

**Comment by GeorgiaHCA** [comment]
@lindsey-depledge are you able to get in touch with Ellen to arrange a meeting? :) Thanks!

**Comment by GeorgiaHCA** [comment]
Closing this as Lindsey has been onboarding and is working with Elleen on user testing
