### ISSUE TITLE
Create Video demo of work done during first sprint

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#116]
Link this to documentation explaining work and decions made
Upload to the main GitHub repo
Disseminate - get in touch with Autistica or Georgia

**Comment by GeorgiaHCA** [comment]
Use Business Requirements to check requirements: 

https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/96/files?short_path=c9026eb#diff-c9026eb62eeb41fd822915481c2faadf

**Comment by fjThomasStanley** [comment]
Video creation will be a Fujitsu Business As Usual (BAU) task that occurs every sprint

**Comment by EllenDevereux** [comment]
Please only use issues for BAU tasks when they haven't occurred by the given deadline.

**Comment by EllenDevereux** [comment]
Chris is sorting this, will be uploaded asap

**Comment by SaimaButt** [comment]
I believe we should have a ticket each session for visibility as we are not directly demoing. We have to wait for the video to be approved.  If we leave a issue open we can move it into the correct  state once the video has been approved by Fujitsu creative team.
