### ISSUE TITLE
Prioritisation with an autistic collaborator

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#117]
Make sure an autistic user is involved in the prioritisation process

**Comment by fjThomasStanley** [comment]
Georgia to confirm community representation in backlog refinement meetings. First meeting will be expected for Tuesday 17th.

**Comment by GeorgiaHCA** [comment]
Heya @driscolle - can you confirm the date/time of the next prioritisation meeting?

**Comment by driscolle** [comment]
Hi Georgia, I believe Saima is sending me the details later today.   As soon as I have the detail I will send the invites out.

Kind Regards,

Emilia Driscoll
Project Manager
MIS - Solution Implementation Directorate
Fujitsu
Mob: +44 (0) 7867821962 or Internally 73 821962
Email: Emilia.Driscoll@uk.fujitsu.com<mailto:firstname.surname@xx.fujitsu.com>
Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK> [Facebook-icon.gif] <http://www.facebook.com/fujitsuuk>  [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  [google-plus-icon.gif] <https://plus.google.com/103287532874520008913/>

**Comment by GeorgiaHCA** [comment]
Fab! Thanks @driscolle

**Comment by EllenDevereux** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/123/files?short_path=0bbd32a#diff-0bbd32a5ca90a42df58cbac94477247e all meeting dates to 10th June are listed in this doc

**Comment by EllenDevereux** [comment]
All user stories have been prioritised with an autistic users involvement. The project shows the prioritisation and we welcome community feedback on updates to these priorities. @GeorgiaHCA can this issue be closed since all initial prioritisation has happened using autistic community feedback?

**Comment by EllenDevereux** [comment]
And the user testing means that the autistic community will be involved in every sprint and can update us anytime.

**Comment by GeorgiaHCA** [comment]
Thanks @EllenDevereux !
