### ISSUE TITLE
User Testing Plans and Resources

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#120]
Here's some things that it might be useful to create for planning out user testing - feel free to add anything else you think would be useful @EllenDevereux and Lindsey 

- [x] user review session guidelines
- [x] proposed questions for user testing sessions
- [x] resources from Autistica about best practice
- [x] user groups - I think it's important to have a diverse group to test the platform with, this will include people from across the autistic spectrum, parents and carers, as well as thoose of different genders, ethnicities, backgrounds, and sexual orientation. Defining the groups it would be important to test with to get a diverse range would be really useful. 
- [x] timetabling sessions throughout the sprint cycle 
- [x] budgeting/payment options
- [x] Add protocol for signing consent forms 

Let me know what you'd be most interested in doing, what you'd like me to work, and where you might need help!

Thanks so much for your support!!

**Comment by EllenDevereux** [comment]
Lindsey and I don't feel comfortable considering questions before we have the materials from Autistica.

**Comment by GeorgiaHCA** [comment]
Thanks @EllenDevereux I sent you an email - did you manage to get in touch with Autistica to get the materials you need? Happy to help!

**Comment by GeorgiaHCA** [comment]
Hiya @EllenDevereux and Lindsey - just wanting to check up on how you're getting on with this - do you have the materials you need from Autistica?

**Comment by EllenDevereux** [comment]
@GeorgiaHCA please speak to Autistica again about resources and payment.

**Comment by GeorgiaHCA** [comment]
Thanks for offering to help @JamesSCTJ ! - Adding you as an assignee!

**Comment by GeorgiaHCA** [comment]
@EllenDevereux I know you've made a start on this, and there's lots more to do once Autistica gets back to us - would you be able to arrange a meeting with @JamesSCTJ to discuss or point him to the work you've done so far? Thanks both 😸
