### ISSUE TITLE
Add documentation of recent meetings to GitHub repo

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#121]
- [ ] Fujitsu backlog prioritisiation meeting
- [ ] Prototype testing
- [x] GDPR meeting minutes with EH
-

**Comment by EllenDevereux** [comment]
@SaimaButt can we review the linked pull request in our meeting.

@GeorgiaHCA can we separate into separate issues with individual pull requests so we don't close this by merging the pull request.

**Comment by GeorgiaHCA** [comment]
Heya @jiraslama would you be able to add the minutes from the meeting with TA to the repo? Thanks!
