### ISSUE TITLE
Update timelines for agile workflow process 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#128]
From sprint planning meeting 2 - timeline changed 

15 day sprints
video to Fujitsu comms on the 12 day
video viewable on day 15

day 1 - retrospective from previous sprint and planning for next sprint 

Adapt the agile process

**Comment by driscolle** [comment]
Thanks for being flexible on the 15day sprint.

**Comment by driscolle** [comment]
[Autistica Sprint Dates.xlsx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4451650/Autistica.Sprint.Dates.xlsx)

**Comment by KirstieJane** [comment]
Thanks @driscolle - that's helpful but it is difficult to search for in the future - so once we have it locked down it would be great to have a screen capture (maybe in two parts as the timeline is so long) stored as an image in the repository.

I'm confused about when the sprints start - the backlog refinement meetings for sprint 4 for example seem to be a long way removed from the sprint actually starting.

@SaimaButt - please could you just capture in a few sentences the logic for the timings of these different meetings? I know @EllenDevereux had a draft of this document somewhere but I don't think it captured this time gap from backlog refinement to sprint planning.

**Comment by SaimaButt** [comment]
@KirstieJane 

1. Backlog refinement meeting happens every week to make sure it is prioritised and all issues have details in there. 
2. Sprint Planning happens every 15th Day example SPrint 3 is on 28th April, 15 days later on 19th May we have Sprint 4 planning
3. Internally on Day 12 we send a demo (video) to Fujitsu creative
4. On Day 15 we send the demo (video) to you and Georgia and community for review
5. Day 15 you provide us with feedback, however the community continue to have a look and provide feedback later.

This is my understanding from the discussion we have had. Hope this makes sense.

![image](https://user-images.githubusercontent.com/56388625/78814853-44ec2180-79c7-11ea-91af-e2c67a70cb0a.png)

**Comment by KirstieJane** [comment]
Thanks @SaimaButt 

I don't think your answer explains why the backlog refinement meetings are coloured according to sprints. If they're happening regularly then they should be their own colour not linked to a sprint, right?

Just an additional note that this issue can't close unless the information captured here is in the repository somewhere. (I just want to avoid that misunderstanding. Having me understand the process is not the same as transparently capturing it for anyone who is participating in the project to see what our processes are.)

**Comment by SaimaButt** [comment]
@KirstieJane  Apologies I'd not realised the query was also regarding the colours. I have coloured them the same per sprint to kind of give a guide as to what sprint we are aiming for. Happy to give it its own colour if that makes it easier to understand 

@EllenDevereux correct me if I am wrong but did we not capture the dates in the repository under project_management folder?

**Comment by KirstieJane** [comment]
This work has been addressed in #156. Once that is ready for review (when it doesn't say [WIP] in the title) please check that PR. Once it is merged this issue can close.
