### ISSUE TITLE
Get comfortable with GitHub

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#129]
### I would like to...
be able to use GitHub 

### Because...
we need to understand the project completely

### Acceptance criteria
everyone can use GitHub
documentation for other users

---

**Comment by EllenDevereux** [comment]
We have a meeting this afternoon to do this.

**Comment by EllenDevereux** [comment]
Meeting was carried out. Issue is staying open for the rest of the sprint at least to allow @SaimaButt & Emilia to raise any queries in retrospect.

**Comment by SaimaButt** [comment]
On going but feel alot more confident with Github
