### ISSUE TITLE
Document Fujitsu meeting dates 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#132]

**Comment by driscolle** [comment]
Hi the sprint plan dates have been provided to me, tomorrow I will be defining the agenda for each with Saima and get the meeting invites out to you all.

**Comment by KirstieJane** [comment]
This work has been addressed in #156. Once that is ready for review (when it doesn't say [WIP] in the title) please check that PR. Once it is merged this issue can close.
