### ISSUE TITLE
Sort out pull request #95

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#133]
There's some amazing work, but multiple pull requests were created - possible to tidy these up @JamesSCTJ ? 😸  Happy to help if you need!

**Comment by JamesSCTJ** [comment]
Umm, yes please

**Comment by KirstieJane** [comment]
@GeorgiaHCA - I can try to unpick this and do the GitHub part if you and @JamesSCTJ can ping me the files you'd like to upload ✨  It's very easy to get into a bit of an exciting mess with pull requests all over the place!

You could also ask some of the other Whitaker Lab members to help if they have capacity 💖

**Comment by JamesSCTJ** [comment]
@KirstieJane @GeorgiaHCA 

Thanks, I'll try and fine the intended file from the chaos! Definitely get me to stress test the platform before it goes online because I will create problems that nobody has ever seen in the history of software!

**Comment by GeorgiaHCA** [comment]
Heya @JamesSCTJ - you are doing great!!! Thanks for all your help :)
