### ISSUE TITLE
Write an April Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#134]
Write a newsletter for April to send out to mailing list

**Comment by GeorgiaHCA** [comment]
This has been sent to KW and OS for review

**Comment by GeorgiaHCA** [comment]
@JamesSCTJ please can you help review? Thank you! I've included your tips on dealing with lockdown :)

**Comment by JamesSCTJ** [comment]
Sure can!
