### ISSUE TITLE
Useful resources for accessibility

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#14]
* https://accessibility.blog.gov.uk/2019/02/11/using-persona-profiles-to-test-accessibility/
* https://www.plymouth.ac.uk/about-us/teaching-and-learning/inclusivity/how-can-i-be-more-inclusive

**Comment by GeorgiaHCA** [comment]
Heya @KirstieJane - me and Ellen are doing some GitHub Spring cleaning - would you like us to create a markdown file to hold resources?

**Comment by GeorgiaHCA** [comment]
Closing this issue as the resources have been addded to the resources folder: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/Resources/README.md
