### ISSUE TITLE
Create Agenda / Template

### ISSUE THREAD

**Issue by driscolle** [alan-turing-institute/AutisticaCitizenScience#143]
I am going to create a new folder for future meeting agendas.

**Comment by GeorgiaHCA** [comment]
Great, thanks @driscolle !

**Comment by driscolle** [comment]
[Austistica Scrum Ceremonies Template.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4450470/Austistica.Scrum.Ceremonies.Template.docx)

SAima and I have discussed and this is the Agenda Template to be used going forwards.

**Comment by KirstieJane** [comment]
This work has been addressed in #156. Once that is ready for review (when it doesn't say [WIP] in the title) please check that PR. Once it is merged this issue can close.
