### ISSUE TITLE
Functional Testing guidelines 

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#145]
Unit or regression testing.

The process and tooling needs to be defined.

**Comment by SaimaButt** [comment]
Moving to backlog to discuss the process for Sprint 3/4

**Comment by SaimaButt** [comment]
Hi @pgc007  Please can you add the link to the document and then move this issue to In-Review state. Thanks

**Comment by GeorgiaHCA** [comment]
Thanks @pgc007 - are you able to open a pull request to the main repository to merge changes from that branch, and then link the pull request to this issue? That would really help review! Thanks! Georgia

**Comment by SaimaButt** [comment]
@fjThomasStanley please can you link the pull request for the document and then over the issue to the correct state. Thanks

**Comment by georgepstaylor** [comment]
Branch for latest changes is here: https://github.com/alan-turing-institute/AutisticaCitizenScience/commits/Testing-TSPatch

**Comment by SaimaButt** [comment]
The work has been delivered via https://github.com/alan-turing-institute/AutisticaCitizenScience/commits/Testing-TSPatch which has a pull requested created
