### ISSUE TITLE
Turn user stories from google docs sheet into issues on main GitHub repo

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#148]
Hey @fjThomasStanley, let's put the user stories as issues on the main GitHub repo for openness and transparency :)

**Comment by fjThomasStanley** [comment]
@GeorgiaHCA Absolutely agree, however before we do this and as agreed in our Google doc update meeting today, I need to ensure all information from the focus group meetings held last year are properly processed in the google sheet. @EllenDevereux and myself will look to move the User Stories into GitHub as issues next week.

**Comment by EllenDevereux** [comment]
create a README file

**Comment by fjThomasStanley** [comment]
This is a long running process that occurs throughout the whole project and shouldn't be tied to the timescale of a particular sprint.

**Comment by anirudh4792** [comment]
@GeorgiaHCA I was wondering where I could find the user stories google docs sheet. I assume this is different from project management / User stories and requirements (RCTM guide). Thanks

**Comment by GeorgiaHCA** [comment]
Hiya Anirudh! The google docs sheet is where the focus groups have been written up into user stories, but they should all be in issues. @fjThomasStanley - could you share the google doc with Anirudh? Maybe he can help you to turn them into issues. Thanks!
