### ISSUE TITLE
AT feedback on demo

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#158]

**Comment by SaimaButt** [comment]
Sprint report to be supported with the Demo for feedback to be given

**Comment by EllenDevereux** [comment]
Sprint report is as finished as it can be at this point

**Comment by SaimaButt** [comment]
This is a task which is ongoing for every sprint therefore will close this as it related to Sprint 1 - 3 and will create a new issue each time for future sprints
