### ISSUE TITLE
Create a README.md file which collates all of the documentation on how all user stories are created

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#160]

**Comment by EllenDevereux** [comment]
Include all of @fjThomasStanley documentation in a set of files

**Comment by GeorgiaHCA** [comment]
Rough outline of process as I understand it is as follows: 

1. Focus Groups held
2. Focus Groups transcribed, summarised, reviewed by participants and published on GitHub
3. Go through summaries and select insights which can be made into user stories
4. Turn these into user stories and publish as issues on the main GitHub repo
5. Add acceptance criteria to user stories (input from autistic community collaborator)
6. Link all issues to README which explains process and links to  FG summaries folder, and prioritisation/sprint documentation
7. Prioritise issues (involve autistic collaborator in process) and document (how does the prioritisation happen?)
8. Take prioritised issues into backlog each sprint and label as Fujitsu’s tasks

There will also be some user stories which aren't from the focus groups and some tasks which aren't user stories, all of which should be published as issues on GitHub as well (explain this in documentation)

It would be great to make this as clear as possible for outside collaborators and researchers to trace the process- imagine a recipe for someone wanting to reproduce the process. Happy to help as needed/review!

Thanks for your hard work everyone :-D

**Comment by SaimaButt** [comment]
@fjThomasStanley to include the milestone information
