### ISSUE TITLE
List of questions for community

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#163]
@fjThomasStanley to create a markdown of questions for community from googledoc

**Comment by jiraslama** [comment]
To be circulated to networks when community-questions.md is live!
 
Welcome… 
 
We wanted to introduce you to a new project, Autistica’s Citizen Science Platform if you were not already aware of it. We are co-designing an online platform to investigate the experiences of autistic people as they navigate the world around them. This is to find ways to improve environments for autistic people and their families, for example workplaces, schools, and hospitals. 
 
This tool could have a huge impact on people's lives, but we cannot build it without the input of a diverse community of autistic people, their relatives and carers. We also welcome open source developers to help us build this platform. 
 
General information about the project: https://alan-turing-institute.github.io/AutisticaCitizenScience/
 
 
Feedback
 
The development team have started working and are using insights from the community to design the platform. We need feedback from the community on these designs for the first three fortnights worth of work (these fortnights are called "Sprints"), and into the future. You can let us know what you think of what has already been made and use your feedback for the next stages of the design. You can also be involved directly in the design work yourself if you would like to! You can be as involved as you would like. 
 
Your feedback would be very much appreciated, and would help develop a platform for the autistic community that could change people's lives. 
 
To take part, all you have to do is watch some videos for ideas for the platform and answer some questions about it.  If you have anything you want to say that isn't related to one of the questions you can also let us know that. The questions are just prompts! We would be really grateful for your thoughts. Just follow this link to get started:
 
https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience/blob/communityquestions/project-management/wireframes/updated-questions.md


(once new questions are agreed, this will be committed to Turning branch removing fj)
 
You can also email researcher Georgia Aitkenhead at gaitkenhead@turing.ac.uk, or User Experience Designer Christopher Legg at christopher.legg@fujitsu.com, if you have any questions or would prefer to send your feedback by email. 
 
Thank you for responding to this email. 
 
Kind regard,
 
[name]

**Comment by SaimaButt** [comment]
This is linked to #179

**Comment by SaimaButt** [comment]
Documented but need to move into GitHub @jiraslama

**Comment by GeorgiaHCA** [comment]
I've made a few small recommended changes to the PR - I like the questions and I think the instructions are now pretty clear

**Comment by GeorgiaHCA** [comment]
Definitely worth having there and we can iterate (and maybe add more words to the glossary) as we get more feedback?
