### ISSUE TITLE
Translatable platform

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#166]
### I would like to...

A method of decoupling the string values used in the platform interface from the application source code.

### Because...

the community requirement of having an easily translatable interface can be met.

### Acceptance criteria

Suitable for web based application.

* Research to understand Translations in Django
* Coding Standards for Django

---

### Sources 

This user story was created by combining multiple insights from focus groups held in Autumn 2019. These focus groups were a mixture of autistic people, their families, and people from Autistica, the Turing, and Fujitsu. The data from the focus groups and more details about how it was collected and processed can be found here: [Focus Groups](AutisticaCitizenScience/community-recommendations/focus-groups). For this user story, the specifically, the following comments were used: FG18-09-2019 3.a) & FG04-10-2019 8.a)

More details about the process by which this user story was created from the sources can be found here.

**Comment by GeorgiaHCA** [comment]
Heya! Thanks for the session extra early this morning @EllenDevereux I really appreciate it! 😸 I think if all the user stories which have them as a source have a link to the focus group summaries, and the documentation that @fjThomasStanley is writing, that would be great!

**Comment by GeorgiaHCA** [comment]
Hey @EllenDevereux - made a few edits to the user story comment so it's slightly less enigmatic :tulip: - you can just copy and paste the sentence for other user stories and change the specific references

**Comment by EllenDevereux** [comment]
A link will be added to process documentation asap. #160

**Comment by georgepstaylor** [comment]
Django docs on localisation:

https://docs.djangoproject.com/en/3.0/topics/i18n/translation/

**Comment by georgepstaylor** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/275/
