### ISSUE TITLE
Document the process of how we will get feedback from the community

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#176]
How do we get feedback from the community

Suggestions
- Questionnaire which includes from individuals
- Send video and newsletter to community people who signed up for this at the start of the project.

### Update on 19 May

- [ ] Link to the videos from the GitHub repository and associated website (which is built from the GitHub repository so that the videos and sprint reports are easy to find.

**Comment by SaimaButt** [comment]
Document is still outstanding. Work with @jiraslama to determine the acceptance criteria

**Comment by SaimaButt** [comment]
This is complete @jiraslama  to link pull request

**Comment by jiraslama** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/jiraslama-patch-1/project-management/wireframes/feedback-mechanism.md

project-management/wireframes/feedback-mechanism.md


Now commited to fj branch waiting approval to main Autistica Core Project Branch 

https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience/blob/documentation/project-management/wireframes/feedback-mechanism.md

**Comment by GeorgiaHCA** [comment]
This has been merged already - I did a reformatted version and added it to the file here: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/wireframes/feedback-mechanism.md I think it will need more detail?

**Comment by GeorgiaHCA** [comment]
Closing this issue as the feedback mechanism has been merged to master and is now being incorporated through reorganising the repo - see #305. Thanks for all your amazing work on this @jiraslama
