### ISSUE TITLE
Run GitHub session for Fujitsu team 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#205]
Heya @malvikasharan ! Thanks for offering to run a GitHub tutorial for the Fujitsu team - it would be really great!

If you're still up for it, when would be a good time for you?

**Comment by malvikasharan** [comment]
Hey Georgia, Happy to run this :) My week starting 25 May and 1 June are better than the next ones.

**Comment by GeorgiaHCA** [comment]
Brilliant Malvika! That's wonderful. I really looking forward to it! @SaimaButt - when woud be good for the Fujitsu team?

**Comment by SaimaButt** [comment]
@GeorgiaHCA tomorrow at 3:00pm will be good. If you can set it up that will be great.

**Comment by malvikasharan** [comment]
Hi @SaimaButt, I won't be available tomorrow. Would you have a preferred date time in the week starting 25 May or  1 June?

**Comment by SaimaButt** [comment]
Hi @malvikasharan Wednesday 27th is a good day - anytime after 11am

**Comment by malvikasharan** [comment]
I can block 13:00 - 14:00 on 27 May for this.

**Comment by SaimaButt** [comment]
Thanks @malvikasharan  - can you send out the invite @GeorgiaHCA please.

**Comment by GeorgiaHCA** [comment]
Hey @Ismael-KG - adding you to the thread - hope you can make it!

**Comment by SaimaButt** [comment]
@GeorgiaHCA  will you be setting up a meeting invite, as I do not have the email addresses for the other participants.

**Comment by SaimaButt** [comment]
This was completed on 27th May
