### ISSUE TITLE
Test - Welcome Bot

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/AutisticaCitizenScience#211]
I am a new contributor opening an issue to test welcome bot

**Comment by GeorgiaHCA** [comment]
Ah, I'm sorry @Ismael-KG - looks like we'll have to continue working on the integration - in the meantime, anything you think it would be useful to know or be directed to as a new contributor would be really great to know! Thanks for your help 🌟

**Comment by malvikasharan** [comment]
Oh nooo! I don't know why this is not working. I retried on a new fork with these steps and it worked: https://github.com/malvikasharan/AutisticaCitizenScience/issues/2

1) Configure welcome bot by giving it access to your repo
2) create a config.yml file with the content
3) test if they work!
