### ISSUE TITLE
Organise focus groups for September

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#22]
We have ethics approval! Let start asking folks what we should build and how they would like to interact with the platform ✨

**Comment by GeorgiaHCA** [comment]
Dates/times/location/refreshments arranged (thanks CH!) and co-facilitator in place (thanks to BD!). Autistica will recruit for them.

**Comment by GeorgiaHCA** [comment]
[Focus Group Schedule.pdf](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/3677132/Focus.Group.Schedule.pdf)

This is the schedule we put together for the first two focus groups

**Comment by JamesSCTJ** [comment]
Georgia HCA- Done I think?
