### ISSUE TITLE
Build wireframe

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#23]
Lets build a wireframe to guide development of the platform.

Tagging @akeshavan to find out the resource she used to build a wireframe.

I think it also makes sense to collect together a paragraph or two about _why_ wireframes are so important.

**Comment by fjThomasStanley** [comment]
Please see a prototype wireframe I have made for the platform. This wireframe has been developed during the Focus Group sessions hosted at Fujitsu:

Heroku Host:
https://fjautisticaexperiences.herokuapp.com

Source Code:
https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience

**Comment by JamesSCTJ** [comment]
Georgia HCA, I suspect this should be high priority and assigned to Fujitsu?

**Comment by fjThomasStanley** [comment]
This issue is very similar to issue #103 - Create Wireframes. #103 was closed via #102 and maybe this issue needs closing as well based on this.

**Comment by GeorgiaHCA** [comment]
This issue is now closed as the Fujitsu wireframe has been completed. Thanks for everyone's work on this!
