### ISSUE TITLE
Document what development tool we plan to use

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#237]
**As a** member of the community
**I would** like to understand why we have chosen a specific development tool
**So that** i can see the pros and cons

**Acceptance Criteria**
1. List the development tool we will be using
2. Each development tool should include a description of what that tool will do.
3. Each development tool must illustrate its benefits for using
4. Each development tool must illustrate its cons for using

**Comment by SaimaButt** [comment]
Hi @KirstieJane I have created this issue but the team wanted to clarify why this document was  needed as the suggestion to use Django came from you. Therefore we started to use Django. If there are other development tools that have more pros; are you saying you are happier for us to use that.

**Comment by GeorgiaHCA** [comment]
Heya @SaimaButt - just checking if there's a pull request for this issue. If so could you link it? I'll put this back to "to do" for now because I think Kirstie's already given feedback on it? Thank you! :) Georgia

**Comment by georgepstaylor** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/270

**Comment by georgepstaylor** [comment]
Hi @GeorgiaHCA - Created and linked the PR 😊

**Comment by GeorgiaHCA** [comment]
Thanks @georgepstaylor 😸

**Comment by GeorgiaHCA** [comment]
I think I may be in a PR/issue loop as this links to the big PR that needs to be broken into smaller ones?
