### ISSUE TITLE
Incorporate changes recommended by LC in her project review

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#24]
The review that LC provided was really excellent and had some great suggestions for improving some of the processes for this project.

@GeorgiaHCA - please can you create a new branch in this repository and update the files in the `project_management` directory to reflect those changes (and any others that we've recieved).

Lets aim to submit a ethics ammendment on September 1 (or thereabouts). ✨

**Comment by GeorgiaHCA** [comment]
Files have been updated in pull requests. They're in doc form with comments - can put into pdf once reviewed and re-upload :)

**Comment by GeorgiaHCA** [comment]
Just updated the google forms survey

**Comment by EllenDevereux** [comment]
@KirstieJane this might need ethics amendment. Please can you review.
