### ISSUE TITLE
Create Cartoon or video to help people contribute

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#25]

**Comment by EllenDevereux** [comment]
Can anyone in the community offer assistance with this?

**Comment by GeorgiaHCA** [comment]
Check out "The Great I Said No"  - Stoppit and Tidyup series, voiced by Terry Wogan: 

https://www.youtube.com/watch?v=9pbIriBC60U

Characters with the name of what they represent on this T-Shirt: have one for each label

**Comment by GeorgiaHCA** [comment]
Possibly insight group member? Participation in GitHub
