### ISSUE TITLE
Development framework design decision documentation

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#254]
### I would like to...

a document that discusses the design decisions and justification relating to choice of development framework for the platform

### Because...

I want to understand the decision making behind why a particular development technology is chosen for this project over other suitable technologies. The project has to be maintainable and sustainable beyond and a document design decisions would enable this.

### Acceptance criteria

Document formatted as a markdown file and uploaded into the project-managment/platform-requirements area of the Github repository.

Topics to be covered include:

- Comparisons of popular development frameworks
- Why a particular framework is chosen for development over others discussed in the document

### Other relevant documents
Values
Ways of working

### Review owner/s
An external member of the open source community
Alan Turing - @KirstieJane 

---

## Notes

* Associated pull request: WRITE HERE
* Current status: WRITE HERE

---

**Comment by georgepstaylor** [comment]
https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience/blob/development-tools/project-management/Technical%20Docs/development-tools.md

**Comment by jiraslama** [comment]
https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience/blob/documentation/project-management/wireframes/design-decisions.md
