### ISSUE TITLE
Fujitsu Wireframe design: Modular alerts for timeout save

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#260]
### I would like

A wireframe design and justification that showcases the Modular alerts for timeout save platform component

### Because...

I would like show to the wider community a Fujitsu design concept for the platform

### Acceptance criteria

Axure updated with the final UI design for the component
A picture/screenshot image of the final UI design of the component held within Axure
Justification of the component design available in Github repository as an md file  

### Other relevant documents:
Values
Ways of working
Data management
Focus group summaries

### Review owner:
Internal development team
Alan Turing

**Comment by jiraslama** [comment]
Live Dev View of Alert screens as images

https://c6q95y.axshare.com/#g=1&p=8-modular-alerts-timeout-save&view=default

Functionality View

https://c6q95y.axshare.com/#g=1&p=8-3_-_add-event-alert&view=default

Experience page across devices with alert overlays you can view the functionality of the modular overlay fade animation by clicking on alert button. The alert also has a close icon which goes page to the experience page.

https://c6q95y.axshare.com updated wireframe

**Comment by jiraslama** [comment]
02072020 - Paul has completed a great alet inline with wireframe. It has been recommended that he explores its implementation across device (responsive). iphone, ipad and large screen as wireframe above. George has offered to support this as required.

**Comment by GeorgiaHCA** [comment]
Hiya @jiraslama, @fjThomasStanley - if possible could you please add the community sources which led to the creation of this issue? Thank you! :-D Georgia

**Comment by jiraslama** [comment]
Data Entry, General User, Timeout Save, Have the option to pull out while in the process of submitting information before the whole form is finished, I can leave if I want or need to without previous information being lost, User -Timeout Save after 10 minutes of inactivity the user is given a prompt after a further 2 minutes a prompt appears stating the experience has been saved as a draft - save / draft settings within core Settings.

This examples layout is the format which will be taken for all in app modular alerts.
