### ISSUE TITLE
Fujitsu Wireframe design: Short detail submission

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#261]
### I would like

A wireframe design and justification that showcases the Short detail submission component

### Because...

I would like show to the wider community a Fujitsu design concept for the platform

### Acceptance criteria

Axure updated with the final UI design for the component
A picture/screenshot image of the final UI design of the component held within Axure
Justification of the component design available in Github repository as an md file  

### Other relevant documents:
Values
Ways of working
Data management

### Review owner:
Internal development team
Alan Turing

**Comment by SaimaButt** [comment]
@jiraslama to make some wireframe designs and @GeorgiaHCA  to talk to Kirstie about community input

**Comment by GeorgiaHCA** [comment]
We consulted and decided this was better left to later on in the project after we have created a bare bones version so we can get the basic infrastructure in place first. Still really a great thing to keep in mind @fjThomasStanley. Can you please add the community source for his issue? Thanks!

**Comment by jiraslama** [comment]
Research Deck

![Short-Detail-Submission-deck 001](https://user-images.githubusercontent.com/41741006/87244004-b5756500-c432-11ea-8806-e4273db67303.png)
![Short-Detail-Submission-deck 002](https://user-images.githubusercontent.com/41741006/87244005-b73f2880-c432-11ea-8688-22bbf76b9bbf.png)
![Short-Detail-Submission-deck 003](https://user-images.githubusercontent.com/41741006/87244007-b908ec00-c432-11ea-9489-d2c1de4c6352.png)
![Short-Detail-Submission-deck 004](https://user-images.githubusercontent.com/41741006/87244011-bd350980-c432-11ea-9662-64f48f701785.png)
![Short-Detail-Submission-deck 005](https://user-images.githubusercontent.com/41741006/87244013-be663680-c432-11ea-99a9-f4d6b8331a69.png)
![Short-Detail-Submission-deck 006](https://user-images.githubusercontent.com/41741006/87244014-befecd00-c432-11ea-8cc9-2bf0a887d5c3.png)
![Short-Detail-Submission-deck 007](https://user-images.githubusercontent.com/41741006/87244019-c1612700-c432-11ea-9f25-1f606149880e.png)
![Short-Detail-Submission-deck 008](https://user-images.githubusercontent.com/41741006/87244020-c32aea80-c432-11ea-812f-809350ddf8d4.png)
![Short-Detail-Submission-deck 009](https://user-images.githubusercontent.com/41741006/87244022-c3c38100-c432-11ea-9b83-0de207f61451.png)
![Short-Detail-Submission-deck 010](https://user-images.githubusercontent.com/41741006/87244023-c58d4480-c432-11ea-8f04-643508db410b.png)
![Short-Detail-Submission-deck 011](https://user-images.githubusercontent.com/41741006/87244025-c6be7180-c432-11ea-8896-987c6f3ae458.png)
![Short-Detail-Submission-deck 012](https://user-images.githubusercontent.com/41741006/87244028-c8883500-c432-11ea-9d40-6f1931c09a8f.png)
![Short-Detail-Submission-deck 013](https://user-images.githubusercontent.com/41741006/87244030-ca51f880-c432-11ea-9b9d-ce7f46ecafd8.png)
![Short-Detail-Submission-deck 014](https://user-images.githubusercontent.com/41741006/87244032-cb832580-c432-11ea-9396-13a390644db7.png)
![Short-Detail-Submission-deck 015](https://user-images.githubusercontent.com/41741006/87244033-ccb45280-c432-11ea-98cb-976894c38acf.png)
![Short-Detail-Submission-deck 016](https://user-images.githubusercontent.com/41741006/87244035-cde57f80-c432-11ea-8766-03a92b20f86c.png)
![Short-Detail-Submission-deck 017](https://user-images.githubusercontent.com/41741006/87244038-d047d980-c432-11ea-98cd-c64f82eb2bb2.png)
![Short-Detail-Submission-deck 018](https://user-images.githubusercontent.com/41741006/87244039-d1790680-c432-11ea-875f-9d0911d6b757.png)
![Short-Detail-Submission-deck 019](https://user-images.githubusercontent.com/41741006/87244040-d2119d00-c432-11ea-9135-6e0a24c34ced.png)
![Short-Detail-Submission-deck 020](https://user-images.githubusercontent.com/41741006/87244041-d3db6080-c432-11ea-9ad0-703aa8777338.png)
![Short-Detail-Submission-deck 021](https://user-images.githubusercontent.com/41741006/87244042-d6d65100-c432-11ea-9f5b-4c84f64c7a2b.png)
![Short-Detail-Submission-deck 022](https://user-images.githubusercontent.com/41741006/87244044-d8077e00-c432-11ea-9b09-e186990d84cb.png)
![Short-Detail-Submission-deck 023](https://user-images.githubusercontent.com/41741006/87244045-d8a01480-c432-11ea-9a16-f0f115670239.png)
![Short-Detail-Submission-deck 024](https://user-images.githubusercontent.com/41741006/87244046-d938ab00-c432-11ea-804c-ed786f8a47b3.png)
![Short-Detail-Submission-deck 025](https://user-images.githubusercontent.com/41741006/87244047-d9d14180-c432-11ea-9bec-d29fb842b277.png)
![Short-Detail-Submission-deck 026](https://user-images.githubusercontent.com/41741006/87244048-da69d800-c432-11ea-8c98-da0c56bed276.png)
![Short-Detail-Submission-deck 027](https://user-images.githubusercontent.com/41741006/87244049-db026e80-c432-11ea-8550-18b5919ab597.png)
![Short-Detail-Submission-deck 028](https://user-images.githubusercontent.com/41741006/87244050-db9b0500-c432-11ea-9876-fb9084c5ce34.png)
![Short-Detail-Submission-deck 029](https://user-images.githubusercontent.com/41741006/87244051-dccc3200-c432-11ea-9804-53df06a763be.png)
![Short-Detail-Submission-deck 030](https://user-images.githubusercontent.com/41741006/87244053-ddfd5f00-c432-11ea-89c5-b7ad43179281.png)
![Short-Detail-Submission-deck 031](https://user-images.githubusercontent.com/41741006/87244054-dfc72280-c432-11ea-9eda-95ff1c0a4737.png)
![Short-Detail-Submission-deck 032](https://user-images.githubusercontent.com/41741006/87244055-e05fb900-c432-11ea-8baa-45e0540279bb.png)
![Short-Detail-Submission-deck 033](https://user-images.githubusercontent.com/41741006/87244057-e0f84f80-c432-11ea-99b0-ab5185eea066.png)
![Short-Detail-Submission-deck 034](https://user-images.githubusercontent.com/41741006/87244058-e35aa980-c432-11ea-9dd1-5737078cec63.png)
![Short-Detail-Submission-deck 035](https://user-images.githubusercontent.com/41741006/87244060-e5bd0380-c432-11ea-8992-383bf9ea742c.png)
![Short-Detail-Submission-deck 036](https://user-images.githubusercontent.com/41741006/87244061-e6ee3080-c432-11ea-8cb5-092d3ec3c178.png)
![Short-Detail-Submission-deck 037](https://user-images.githubusercontent.com/41741006/87244062-e81f5d80-c432-11ea-9037-1d5273258311.png)
![Short-Detail-Submission-deck 038](https://user-images.githubusercontent.com/41741006/87244064-e9e92100-c432-11ea-9942-2db948161e50.png)
![Short-Detail-Submission-deck 039](https://user-images.githubusercontent.com/41741006/87244067-eeadd500-c432-11ea-9bd2-67b117f7ef82.png)
![Short-Detail-Submission-deck 040](https://user-images.githubusercontent.com/41741006/87244070-ef466b80-c432-11ea-9b62-abc5e273d150.png)
![Short-Detail-Submission-deck 041](https://user-images.githubusercontent.com/41741006/87244071-f1102f00-c432-11ea-96b9-efcad61100de.png)
![Short-Detail-Submission-deck 042](https://user-images.githubusercontent.com/41741006/87244074-f40b1f80-c432-11ea-9cbe-cd995c1bcfde.png)
![Short-Detail-Submission-deck 043](https://user-images.githubusercontent.com/41741006/87244077-f5d4e300-c432-11ea-9485-93abb39eadb3.png)
![Short-Detail-Submission-deck 044](https://user-images.githubusercontent.com/41741006/87244078-f7061000-c432-11ea-8458-fecf56b43652.png)
![Short-Detail-Submission-deck 045](https://user-images.githubusercontent.com/41741006/87244079-f8373d00-c432-11ea-8cc6-26dad16f1dad.png)
![Short-Detail-Submission-deck 046](https://user-images.githubusercontent.com/41741006/87244081-fa999700-c432-11ea-8c4a-ece797fb7423.png)
![Short-Detail-Submission-deck 047](https://user-images.githubusercontent.com/41741006/87244082-fc635a80-c432-11ea-8b82-176d3effe331.png)
![Short-Detail-Submission-deck 048](https://user-images.githubusercontent.com/41741006/87244083-fe2d1e00-c432-11ea-80cd-6b5a069c4a87.png)
![Short-Detail-Submission-deck 049](https://user-images.githubusercontent.com/41741006/87244084-fec5b480-c432-11ea-96be-c9090bb903d6.png)
![Short-Detail-Submission-deck 050](https://user-images.githubusercontent.com/41741006/87244085-fff6e180-c432-11ea-9836-4579dc44b4c6.png)
![Short-Detail-Submission-deck 051](https://user-images.githubusercontent.com/41741006/87244087-01c0a500-c433-11ea-8ef9-fe9efa5f6e7f.png)
![Short-Detail-Submission-deck 052](https://user-images.githubusercontent.com/41741006/87244088-02f1d200-c433-11ea-9e26-8d0c8deb5437.png)
![Short-Detail-Submission-deck 053](https://user-images.githubusercontent.com/41741006/87244091-0422ff00-c433-11ea-9ac5-f0fba13f4f00.png)
![Short-Detail-Submission-deck 054](https://user-images.githubusercontent.com/41741006/87244092-05542c00-c433-11ea-8137-0a8a18d62641.png)
![Short-Detail-Submission-deck 055](https://user-images.githubusercontent.com/41741006/87244093-05ecc280-c433-11ea-871e-2db8c6529a17.png)
![Short-Detail-Submission-deck 056](https://user-images.githubusercontent.com/41741006/87244095-07b68600-c433-11ea-9785-e8fb9bf2cd37.png)
![Short-Detail-Submission-deck 057](https://user-images.githubusercontent.com/41741006/87244096-084f1c80-c433-11ea-9cf8-366aef5985c6.png)
![Short-Detail-Submission-deck 058](https://user-images.githubusercontent.com/41741006/87244098-0a18e000-c433-11ea-9df9-e765cc631319.png)
![Short-Detail-Submission-deck 059](https://user-images.githubusercontent.com/41741006/87244102-0c7b3a00-c433-11ea-8d00-b1ca21275f90.png)
![Short-Detail-Submission-deck 060](https://user-images.githubusercontent.com/41741006/87244103-0edd9400-c433-11ea-98b7-619080f6eae7.png)
![Short-Detail-Submission-deck 061](https://user-images.githubusercontent.com/41741006/87244104-100ec100-c433-11ea-8d63-2a4ea9e4e7a2.png)
![Short-Detail-Submission-deck 062](https://user-images.githubusercontent.com/41741006/87244105-10a75780-c433-11ea-97d3-d969de7dd57b.png)
![Short-Detail-Submission-deck 063](https://user-images.githubusercontent.com/41741006/87244106-11d88480-c433-11ea-8789-aa68ae60b410.png)
![Short-Detail-Submission-deck 064](https://user-images.githubusercontent.com/41741006/87244107-12711b00-c433-11ea-8140-04d0c8145de4.png)
![Short-Detail-Submission-deck 065](https://user-images.githubusercontent.com/41741006/87244108-143ade80-c433-11ea-8759-522173403e57.png)
![Short-Detail-Submission-deck 066](https://user-images.githubusercontent.com/41741006/87244110-169d3880-c433-11ea-8085-c2adb29d602f.png)
![Short-Detail-Submission-deck 067](https://user-images.githubusercontent.com/41741006/87244113-17ce6580-c433-11ea-82de-8dd6899b9565.png)
![Short-Detail-Submission-deck 068](https://user-images.githubusercontent.com/41741006/87244114-1866fc00-c433-11ea-8b64-db22165c2712.png)
![Short-Detail-Submission-deck 069](https://user-images.githubusercontent.com/41741006/87244115-19982900-c433-11ea-891e-7936bb7282c7.png)
![Short-Detail-Submission-deck 070](https://user-images.githubusercontent.com/41741006/87244118-1b61ec80-c433-11ea-96f8-7f99a4cbabcb.png)
![Short-Detail-Submission-deck 071](https://user-images.githubusercontent.com/41741006/87244119-1bfa8300-c433-11ea-9c58-1c1cfd43fbf3.png)
![Short-Detail-Submission-deck 072](https://user-images.githubusercontent.com/41741006/87244122-1dc44680-c433-11ea-9e59-8e54d3e93851.png)
![Short-Detail-Submission-deck 073](https://user-images.githubusercontent.com/41741006/87244124-1ef57380-c433-11ea-9cbd-7a845c02cd9f.png)
![Short-Detail-Submission-deck 074](https://user-images.githubusercontent.com/41741006/87244125-20bf3700-c433-11ea-8bdb-855c43f5dfba.png)
![Short-Detail-Submission-deck 075](https://user-images.githubusercontent.com/41741006/87244126-21f06400-c433-11ea-8b74-0b5ac2d4b81c.png)
![Short-Detail-Submission-deck 076](https://user-images.githubusercontent.com/41741006/87244127-23ba2780-c433-11ea-89e2-69dbe59fa847.png)
![Short-Detail-Submission-deck 077](https://user-images.githubusercontent.com/41741006/87244129-2583eb00-c433-11ea-809c-577fbbdf3962.png)
![Short-Detail-Submission-deck 078](https://user-images.githubusercontent.com/41741006/87244130-261c8180-c433-11ea-9f0e-cff67c3b1247.png)
![Short-Detail-Submission-deck 079](https://user-images.githubusercontent.com/41741006/87244131-26b51800-c433-11ea-98bd-32d581e54576.png)
![Short-Detail-Submission-deck 080](https://user-images.githubusercontent.com/41741006/87244132-287edb80-c433-11ea-87d5-e6bafe1efb46.png)
![Short-Detail-Submission-deck 081](https://user-images.githubusercontent.com/41741006/87244133-2ae13580-c433-11ea-972e-faa22934f568.png)
![Short-Detail-Submission-deck 082](https://user-images.githubusercontent.com/41741006/87244134-2c126280-c433-11ea-897d-8c7a66664d08.png)
![Short-Detail-Submission-deck 083](https://user-images.githubusercontent.com/41741006/87244135-2ddc2600-c433-11ea-8d03-873d08e74a9f.png)
![Short-Detail-Submission-deck 084](https://user-images.githubusercontent.com/41741006/87244136-2e74bc80-c433-11ea-93b2-8685713d2984.png)
![Short-Detail-Submission-deck 085](https://user-images.githubusercontent.com/41741006/87244139-303e8000-c433-11ea-960e-4917765781e4.png)
![Short-Detail-Submission-deck 086](https://user-images.githubusercontent.com/41741006/87244141-316fad00-c433-11ea-9585-6e038b49dac5.png)
![Short-Detail-Submission-deck 087](https://user-images.githubusercontent.com/41741006/87244142-32084380-c433-11ea-924e-5de75c2a9052.png)
![Short-Detail-Submission-deck 088](https://user-images.githubusercontent.com/41741006/87244143-32084380-c433-11ea-91ab-79923d916492.png)
![Short-Detail-Submission-deck 089](https://user-images.githubusercontent.com/41741006/87244147-33d20700-c433-11ea-99a5-79828593b302.png)
![Short-Detail-Submission-deck 090](https://user-images.githubusercontent.com/41741006/87244152-37658e00-c433-11ea-9239-f9b4c4af70d9.png)
![Short-Detail-Submission-deck 091](https://user-images.githubusercontent.com/41741006/87244157-3b91ab80-c433-11ea-8398-07017433e8a6.png)
![Short-Detail-Submission-deck 092](https://user-images.githubusercontent.com/41741006/87244159-3d5b6f00-c433-11ea-9277-45ed9254e268.png)
![Short-Detail-Submission-deck 093](https://user-images.githubusercontent.com/41741006/87244160-3fbdc900-c433-11ea-9721-f68bdde67c4d.png)
![Short-Detail-Submission-deck 094](https://user-images.githubusercontent.com/41741006/87244164-43515000-c433-11ea-8290-757770d0a596.png)
![Short-Detail-Submission-deck 095](https://user-images.githubusercontent.com/41741006/87244168-45b3aa00-c433-11ea-8cf2-d60d05842efa.png)
![Short-Detail-Submission-deck 096](https://user-images.githubusercontent.com/41741006/87244170-48ae9a80-c433-11ea-954c-e9edab7fb577.png)
![Short-Detail-Submission-deck 097](https://user-images.githubusercontent.com/41741006/87244171-49473100-c433-11ea-9b84-9658623395dd.png)
![Short-Detail-Submission-deck 098](https://user-images.githubusercontent.com/41741006/87244172-49dfc780-c433-11ea-8e93-5b7f3fa6936c.png)
![Short-Detail-Submission-deck 099](https://user-images.githubusercontent.com/41741006/87244173-4a785e00-c433-11ea-8585-97520df11f3e.png)
![Short-Detail-Submission-deck 100](https://user-images.githubusercontent.com/41741006/87244174-4b10f480-c433-11ea-9e7e-84b77d2e16d3.png)
![Short-Detail-Submission-deck 101](https://user-images.githubusercontent.com/41741006/87244175-4c422180-c433-11ea-8c9f-d65762ed4422.png)
![Short-Detail-Submission-deck 102](https://user-images.githubusercontent.com/41741006/87244177-4cdab800-c433-11ea-9f08-7b2f3195178c.png)
![Short-Detail-Submission-deck 103](https://user-images.githubusercontent.com/41741006/87244178-4d734e80-c433-11ea-9d4e-3e1108ad2cc7.png)
![Short-Detail-Submission-deck 104](https://user-images.githubusercontent.com/41741006/87244180-4ea47b80-c433-11ea-8562-4a62192c6461.png)
![Short-Detail-Submission-deck 105](https://user-images.githubusercontent.com/41741006/87244181-4f3d1200-c433-11ea-95c6-d2a7f023191d.png)
![Short-Detail-Submission-deck 106](https://user-images.githubusercontent.com/41741006/87244183-4fd5a880-c433-11ea-86fe-965f4931264c.png)
![Short-Detail-Submission-deck 107](https://user-images.githubusercontent.com/41741006/87244184-506e3f00-c433-11ea-9992-817b089488c9.png)
![Short-Detail-Submission-deck 108](https://user-images.githubusercontent.com/41741006/87244185-519f6c00-c433-11ea-8fe2-cafe00538079.png)

**Comment by jiraslama** [comment]
Series of bare bones versioned wireframe of short submission produced for review by the community based on the research above.  

The wireframe link will follow today.... watch this space !

**Comment by jiraslama** [comment]
https://c6q95y.axshare.com/#g=1&p=add-event-messaging&view=a

Rework following feedback

**Comment by SaimaButt** [comment]
Feedback received from the community,. Issue created which related to this. #356
