### ISSUE TITLE
Fujitsu Wireframe design: Sanctuary location categories

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#263]
### I would like

A wireframe design and justification that showcases the Sanctuary location categories platform component

### Because...

I would like show to the wider community a Fujitsu design concept for the platform

### Acceptance criteria

Axure updated with the final UI design for the component
A picture/screenshot image of the final UI design of the component held within Axure
Justification of the component design available in Github repository as an md file  

### Other relevant documents:
Values
Ways of working
Data management

### Review owner:
Internal development team
Alan Turing

**Comment by fjThomasStanley** [comment]
Backlog Refinement 16/06/2020 - This issue needs to be broken down into sub User Stories
More research required to understand the specific components required for the platform.

**Comment by jiraslama** [comment]
https://github.com/alan-turing-institute/autistica-filemanagement-demo - User Journey Extended from this documentation - ref to specific Moderators Journey

https://c6q95y.axshare.com/#g=1&p=user-journeys&c=1

Wireframe images of 

Moderator User Journey 

Component Notes


Analysis uses for the API
Acces Data Set
Analysis of Data 
Visualisation Methods
Contact not matched when not shared with community 
Contact participate 
Moderation Panel (Core) Process Every experience is moderated by more than one moderator. The moderating process is less individually subjective.
The moderation is reflective of the people who contribute to the platform.
Creates Projects On OH
Can Remove members
Manage User Project Membership
Respond to request to erase all data / cancel project membership as requested 
Completes automatic deletion from db
notifies researchers to delete copies of data 
Analysis uses for the API
Acces Data Set
Analysis of Data 
Visualisation Methods
Contact not matched when not shared with community 
Contact participate 

![user-journey-mod-1](https://user-images.githubusercontent.com/41741006/84870235-f61dd080-b076-11ea-8c09-b9da81caf17a.PNG)
![user-journey-mod-2](https://user-images.githubusercontent.com/41741006/84870251-fb7b1b00-b076-11ea-85bb-199df1e3cee0.PNG)
![user-journey-mod-3](https://user-images.githubusercontent.com/41741006/84870264-00d86580-b077-11ea-80e4-ef51e938a4de.PNG)

**Comment by jiraslama** [comment]
This issue needs clarification.... worth moving to blocked ?

**Comment by jiraslama** [comment]
Further to clarification please find :

Wireframes for review…. 

 4 Sections
 
1. Users location plotted
https://c6q95y.axshare.com/#g=1&p=sensory_categories_section_1

2. Sanctuaries Plotted within radius from the users location
https://c6q95y.axshare.com/#g=1&p=sensory_categories_section_2

3. Search / Filter of categorised sensory mapped events 
https://c6q95y.axshare.com/#g=1&p=sensory_categories_section_3

4 .Mapped Experience Categories - to the location of the user 
https://c6q95y.axshare.com/#g=1&p=sensory_categories_section_4

**Comment by SaimaButt** [comment]
@jiraslama to create a Justification of the component design available in Github repository as an md file
