### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#267]
## Summary

There are a few links in the repository which are broken - this is probably because we need to use relative links for one the repo is updated.

This issue will close when the links in the focus group summaries have been fixed, and we'll open a new one if any more are found.

**Comment by ayrustogaru** [comment]
@GeorgiaHCA can I work on this?

**Comment by GeorgiaHCA** [comment]
Hiya! I've had a go fixing them already - but it would be great if you could double check them to see if they work? Also any comments about how accesible the site is and what would make it easier would be super helpful! I'm trying to think about how to manage the structure at the moment so the folders and documentation all make sense.

**Comment by GeorgiaHCA** [comment]
@ayrustogaru if you would like to help fixing some links you could also help with this issue: https://github.com/alan-turing-institute/AutisticaCitizenScience/issues/161 

Thanks so much :-D

**Comment by ayrustogaru** [comment]
Hi! I've checked the links in the focus group summaries, and a few of them are still pointing to the wrong locations (Ex: the first link under 24th September 2019).

**Comment by GeorgiaHCA** [comment]
Thanks for checking! Are you able to fix it? If you can change the location to the right one and link to this issue as a pull request that would be amazing :)

**Comment by ayrustogaru** [comment]
Sorry, the summary of 24th September was perfect. But, the links in 4th October were pointing to a different branch, i.e, GeorgiaHCA. So I've changed that.

**Comment by GeorgiaHCA** [comment]
Thanks @ayrustogaru! That's really helpful :) I'll add you as a contributor.

**Comment by GeorgiaHCA** [comment]
I've reviewed your pull request and there are just a few changes -really appreciate your help with this!
