### ISSUE TITLE
Make it easier for new contributors

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#274]
## Update

We're now rearranging the folders to make sure they are logical and easy to navigate through. We're using Trello to "draft" reoprganise until we submit a merge:

https://trello.com/b/6oHZ29GA/card-sorting-acsp-github 

## Summary

Improve structure and journey through GitHub repository - so that people can be pointed to the site and understand what the project is about, and how they can contribute. 

## Who can help

Everyone! If you are brand new to the project, or even GitHub in general, you can help by just letting us know what you find good and what you find difficult. Suggestions for improvements welcome.

**Comment by Angelsaur** [comment]
I think you could have Kirsty’s YouTube video right at the start. It explains the project really well. A button linking you to detailed information on the project. A button that says ‘share my experience’.

**Comment by Angelsaur** [comment]
And keep it very simple. At the moment are you asking people for suggestions on how to design the playform itself or for their experiences day to day as an autistic person? Make this very clear :-)

**Comment by GeorgiaHCA** [comment]
Welcome and thanks for your input @Angelsaur! I think we will need to update the video no the README as the project has come quite a long way since it created. I'm really glad you found it explained the project well though. That's very useful to know!

**Comment by katoss** [comment]
We are working on restructuring the GitHub repo to make it easier for new contributors. We are tracking the progress here: #305

**Comment by GeorgiaHCA** [comment]
Heya @SaimaButt - it would be amazing if you could take a look at the work Katharina's been doing - just want to make sure it fits well with your team's work and also we need to co-ordinate to make sure we avoid any merge errors. Thanks and Happy Friday 🌻 Georgia

**Comment by SaimaButt** [comment]
@katoss  this is amazing. I love the use of the trello board as its so easy to follow. Thank you.
