### ISSUE TITLE
Issue Design: Experience Page Result Views / Event Viewer (HP, T) Priority: High Priority MVP

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#294]
## Summary

This is an issue about building a design which allows users to chose different options (a table and a list) for viewing a page which shows people's experiences.

## Community Sources

Throughout the focus groups a number of autistic people and parents of autistic people said that it was important to have different options so that individuals could choose their own preference (see the [community recommendations folder](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/community-recommendations/focus-groups))

Personalisation is also mentioned by the National Autism Society as a part of good website design for autistic people. 

Having different viewing options is therefore important. 

## Who can help

This is a feature which requires technincal skills to develop, however there are lots of options for helping for those without technical skills, like co-designing or reviewing the work. 

## User Story 

As a: Designer, I would like to create for the community a wireframe design with two separate experience views on the same page so the user can toggle between a table and list view whilst being on the experience view page. A toggle function component will be added below the main header in the sub header on the experience view page. The background, header, sub-header and footer will remain static as one single page whilst the content will be viewed in a defined area.
So that the community can provide feedback on the wireframe design, which can be taken into the prototype design stage on the project board as a concept to ensure the platform is being developed in the correct way

Acceptance criteria: 
Review issue designs, research & wireframes take on board area as required. Define how this user story will close
Notes: Associated pull request: Sprint 5 MVP Structure Components to design

**Comment by jiraslama** [comment]
Toggle Event Views  list / table

Link 
https://c6q95y.axshare.com/#g=1&p=5-event-views-together

Screens 
https://c6q95y.axshare.com/#g=1&p=5-toggle-view

Research screens found in considerations design project board

**Comment by jiraslama** [comment]
Moved to ready to review

**Comment by GeorgiaHCA** [comment]
Yay! Thanks @jiraslama 🌟
