### ISSUE TITLE
Issue Design: Sound Submit Prompt

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#296]
As a: 

Designer, I would like to create for the community a wireframe design for the experience page which adds a sound prompt (effect) on the experience page - submit button. Which will alert the user that a experience has been successfully submitted. So that the community can provide feedback on the wireframe design, which can be taken into the prototype design stage on the project board as a concept to ensure the platform is being developed in the correct way

Acceptance Criteria:  Review issue designs, research and wireframes take on board area as required. Define how this user story will close

Notes:  Associated pull request: Sprint 5 MVP Structure (File Management Demo) Components to design - wireframe and then share with developers

Current status: Considerations Design - Design Research Notes Wireframes Interactive & Dev Reference Screens

**Comment by jiraslama** [comment]
Submit Experience - Sound Effect

Function (working effect)
https://c6q95y.axshare.com/#g=1&p=submit-sound-effect

Screen 
https://c6q95y.axshare.com/#g=1&p=6-submit-sound



.Wav on Sharepoint
https://emeia.fujitsu.local/emeia/sites/T31/T1857/Documents/Button_09.wav

**Comment by GeorgiaHCA** [comment]
Heya @jiraslama when you have a moment do you think you could add the community suggestions which led to this issue? Thank you :)

**Comment by jiraslama** [comment]
Surya Teja Togaru, ayrustogaru, https://github.com/ayrustogaru
Sound UI
(A P d): have a satisfying noise when you submit information

**Comment by GeorgiaHCA** [comment]
Thanks @jiraslama 🌻

**Comment by jiraslama** [comment]
Also Reference Original Google Sheet 

Data   Entry | User | Submission  Noise Prompt 
 
The platform to  make a satisfying noise when I submit information .
I know   information I wish to publish has been successfully shared. 

To have a satisfying  noise when I submit information. 

User - Save noise sound effect is heard when a experience is submitted. Consider using standard save sound effect from Windows, (Brain Eno) - related sound library, standard PC computer or Microsoft Apps- sound library, create own effects or source from Motion Array library. 

Review method for  adding sound effect to submit button / action. Discuss with dev. 

Save Sound Effects from Motion Array for example:
   
https://motionarray.com/sound-effects/ui-notifications-573342   https://motionarray.com/sound-effects/accept-sfx-pack-573182   

https://motionarray.com/sound-effects/notifications-573089
