### ISSUE TITLE
Issue Design: Dashboard Notification (C D)

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#299]
## Summary

This issue is a feature of the platform design which is currently being developed by the Fujitsu team. It was chosen because of feedback given in the focus groups and more widely by community members. 

## Who can help

Building this feature requires technical skills, however others can help by reviewing the work or giving their opinions on whether it should be a priority. 

## User story

As a: Designer, I would like to create for the community a wireframe design for the a Dashboard Template which will house a collection of features, whilst focusing on notifications - communications within the system and handle:

When the user last added an experience

How many experiences user has added in the last day, week, month

Comms from researcher or moderator notification

So that the community can provide feedback on the wireframe design, which can be taken into the prototype design stage on the project board as a concept to ensure the platform is being developed in the correct way

Acceptance Criteria:

Review issue designs, research and wireframes take on board area as required.

Define how this user story will close
How many experiences user has added in the last day, week, month

Notes: Associated pull request: Sprint 5 MVP Structure (File Management Demo) Components to design - wireframe and then share with developers

Current Status: Considerations Design - Design Research Notes, Wireframe

**Comment by jiraslama** [comment]
Notifications


Wireframe Functionality 

https://c6q95y.axshare.com/#g=1&p=4-dashboard-notifcations-user-stories


Screens 

https://c6q95y.axshare.com/#g=1&p=9-notifications


Research 

https://c6q95y.axshare.com/#g=1&p=4-dashboard-notification-research1

https://c6q95y.axshare.com/#g=1&p=4-dashboard-notification-research2

**Comment by GeorgiaHCA** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/community-recommendations - it should all be in here

**Comment by jiraslama** [comment]
Re-Review of the focus group data findings.

The review has not indicated any direct reference to dashboard notifications however it has been useful to read these community insights and reference findings again. The focus group data does reference to Platform Design.

To aid clarity a dashboard is a integral part of the user interface  - part of the platform design.

A dashboard is the place where the user will find settings, functions and notifications (alerts to action, read, respond to etc). Further reference to this topic is when the research link above or here.

https://c6q95y.axshare.com/#g=1&p=4-dashboard-notification-research1

https://c6q95y.axshare.com/#g=1&p=4-dashboard-notification-research2
