### ISSUE TITLE
Lightning talk at SciData19

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#30]
I'm on the programme committee so I'd prefer not to speak, but @GeorgiaHCA you could maybe give a talk about the project and its integration with Open Humans?

https://www.springernature.com/gp/campaign/scidata-lightning-talks

**Comment by GeorgiaHCA** [comment]
I sent a submission last week! Looks like it could be a really great opportunity. :)

**Comment by GeorgiaHCA** [comment]
Submission successful! Any ideas for the emphasis of the talk given we only have a short time frame appreciated :)

**Comment by JamesSCTJ** [comment]
Complete I would say Georgia HCA?

**Comment by EllenDevereux** [comment]
@GeorgiaHCA remember to add the nodo link

**Comment by GeorgiaHCA** [comment]
Copying the link here for ease of reference: https://zenodo.org/record/3530454#.Xoc_PxfTXx4

**Comment by GeorgiaHCA** [comment]
The presentation has now been uploaded to the presentations folder
