### ISSUE TITLE
AT Sprint 5 Demo Feedback

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#301]
## Summary 

Every two weeks (called a 'Sprint') the Fujitsu team release a demonstration of the work they've done. This needs to be reviewed by @GeorgiaHCA and @KirstieJane. We also seek feedback from the wider community for each demo sprint - these are addressed in separate issues. 

### As a Fujitsu developer

I want to receive feedback from Alan Turing and the community
So that I know what went well
And what improvements I need to make for future Sprint demos.

### Acceptance Criteria

Alan Turing to attend Retrospective with Fujitsu Developers
Alan Turing to provide feedback on the Retrospective board for the sprint

**Comment by SaimaButt** [comment]
@GeorgiaHCA  are we able to close this issue off now as the retrospectives have been complete for Sprint 5

**Comment by GeorgiaHCA** [comment]
Hey @SaimaButt - yes, of course, happy to! Thanks so much for your work 🌻
