### ISSUE TITLE
Link to Fujitsu filemanagement fork

### ISSUE THREAD

**Issue by georgepstaylor** [alan-turing-institute/AutisticaCitizenScience#302]
## Summary

The Fujitsu development team have been building the platform prototype on top of Open Human's file management system. They have done this by forking a separate repository that contains a demo version of the platform and adapting that. This issue is about linking to that repository. The link to the fork is here: 

https://github.com/fjAutisticaCitizenScience/autistica-filemanagement-demo

## Who can help

This issue is mostly for the Fujitsu team to cover and The Alan Turing Institute to review.

**Comment by GeorgiaHCA** [comment]
I've created another issue around more explicitly linking to the repository and makine it accesible to outside contributors
