### ISSUE TITLE
Community Involvement: Building a Diverse Contributor Base

### ISSUE THREAD

**Issue by katoss** [alan-turing-institute/AutisticaCitizenScience#306]
## Summary
We need to find an easy and effective way to reach out to a diverse group of community contributors to involve them in every step of the development process.

## Date Due by
This issue is part of @katoss summer project work (July - August 2020). However, of course community involement is an ongoing task :) 

## Details
We want to build the Autistica Citizen Science platform **for and together with** people from the autistic community (people with autism, their relatives, carers..). In order to involve the community in every step of the development, we need to find an easy and effective way to reach out to a diverse group of people interested in participating in user tests, surveys, co-design sessions etc. This is not meant to replace the workflow on GitHub, but as an addition: some people might not be comfortable with GitHub and for some purposes - like sending invitations for surveys or user tests - there might be better choices.

## Suggestions for tasks that can fix this issue
* [x] Idea: Create a mailing list with people interested in contributing
* [x] Promote the mailing list
* [x] Figure out other ways to build and maintain a community (ideas welcome <3)

## Who can help
Everyone who has an idea on how to reach out to a diverse group up people, to build and maintain a contributor base. 

If you are interested in becoming part of our contributor base just comment on this issue or write a message to gaitkenhead@turing.ac.uk. (Remark: You can of course also just contribute here on GitHub, no need to "sign up" as a contributor for this! We are just trying to find alternative ways to reach more people, for example for surveys or user tests)

**Comment by GeorgiaHCA** [comment]
We have a mailing list people to the project can sign up to here: https://tinyletter.com/AutisticaTuringCitizenScience. It sends monthly updates and highlights opportunities, but there is no monitoring of diversity, and there are also lots of people who take part who aren't members.

**Comment by GeorgiaHCA** [comment]
Thanks for all your hard work over the summer @katoss - I was delighted you reached a diverse group of people for user testing (inclding BAME, dyslexic, +complex needs and those who are both parents/autistic themselves). The feedback you got from those with diverse needs, perspectives, and backgrounds, addressing some of the more complex aspects of the platform requirements, is hugely appreciated! Closing this issue now as it related specifically to your work - although inclusion will be a permenant feature of the project (and will remain an always-open issue). 🌟 🌟
