### ISSUE TITLE
Fujitsu to translate focus group requirements into issues

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#307]
**As a** Product Owner
**I want** to be able to see all the User Stories that were driven from focus groups
**So that** we can prioritise the requirements accordingly in the backlog refinement sessions.

**Comment by jiraslama** [comment]
Platform Feature Tracking
Screen Grabs and links to Feature Prioritisation & hack.md


Moderation Features - collecting issues - Distillation of focus group statements

Link 

https://hackmd.io/TqqoBku8S9enHFszuc5nag


Screen Grabs 

![image001 (4)](https://user-images.githubusercontent.com/41741006/88049829-b0f52e80-cb4d-11ea-8b0d-cf1c1e16bc86.png)
![image001 (3)](https://user-images.githubusercontent.com/41741006/88049839-b488b580-cb4d-11ea-9626-6ea319b8d9ba.png)
![image001 (1)](https://user-images.githubusercontent.com/41741006/88049840-b5214c00-cb4d-11ea-8b66-ef6d4f2405ec.png)
![image002](https://user-images.githubusercontent.com/41741006/88049842-b5b9e280-cb4d-11ea-8c11-7fd118c7fef0.png)
