### ISSUE TITLE
Add videos and reports for sprint 4 - 6

### ISSUE THREAD

**Issue by katoss** [alan-turing-institute/AutisticaCitizenScience#308]
### I would like to...

easily find out about the current status of the project. At the moment I am only able to find links to the first 3 sprint videos and reports for the first 2 sprints on Github, so I don't know where the project is at at the moment.

### Because...

New contributors need to know where the project is at at them moment, so they can know if and how they can help with something.

### Acceptance criteria

- [ ] links to sprint videos 4 - 6 are on GitHub (update the readme)
- [ ] sprint reports 4 - 6 are on GitHub

**Comment by GeorgiaHCA** [comment]
Heya @jiraslama and @SaimaButt - would either of you b able to do this? It would be really helpful! Thanks

**Comment by katoss** [comment]
Hey @jiraslama, thank you for adding the report and video for sprint 6! 
I noticed that sprint 3 is missing, if you have time, could you add it? It's not so urgent, but it would be good to have it there just for reasons of completeness :)
