### ISSUE TITLE
User Feedback for sprint 6

### ISSUE THREAD

**Issue by katoss** [alan-turing-institute/AutisticaCitizenScience#311]
## Summary
We would like to collect user feedback from community members for the latest wireframes and create guidelines/templates for user tests in the following sprints.

## Date Due by

31/08/2020

## Suggestions for tasks that can fix this issue

- [x] Find +/- 5 community contributors who would like to give feedback (Georgia is going to reach out to some people)

- [x] Plan feedback sessions/mechanisms/questions (It would be perfect if we would schedule a call for this, ideally around 20./21. July)

- [x] Conduct sessions

- [x] Summarise feedback

- [x] Send summaries to participants (they have 2 weeks to request changes)

- [x] Upload to github

- [x] transform into issues

## Who can help

- We are looking for **community members** who would like to give feedback on the latest wireframes and prototypes from sprint 7! If you are intererested, comment here or write an an email to Georgia (gaitkenhead@turing.ac.uk). We plan to also put all instructions on here on GitHub, but this is still a work in progress at the moment.
- Anyone who is interested in planning or summarising user feedback sessions

**Comment by GeorgiaHCA** [comment]
Hey @jiraslama - Katharina would appreciate a call to discuss would you be available?

**Comment by jiraslama** [comment]
Sadly I am working on the Sprint 6 Video and Report today...

**Comment by katoss** [comment]
A little update:
At the moment we are arranging user testing sessions for next week. I will upload the material as soon as it is ready and once the GitHub restructuring has been merged.

**A list of the material that will be uploaded:**
- [ ] The agenda of the user testing sessions for sprint 6
- [ ] A template/guidelines that can be used to create agendas for future sessions
- [ ] Summaries of the user testing sessions

**Next step:**
- [ ] Transform the summaries into issues

**Comment by katoss** [comment]
Another update: @GeorgiaHCA and me held user testing sessions with 5 volunteers and collected lots of feedback :)

We are at the moment in the process of reviewing the summaries of the feedback sessions. Once all of this is finished, we will upload the feedback in the community-recommendations folder (https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/community-recommendations)

**Comment by katoss** [comment]
We  are doing a call tomorrow, 26th August from 11.30am - 1pm (UK time) to talk about turning the user feedback into issues. Comment here or send me a message if you would like to join. Results will of course be published here on GitHub :)

**Comment by GeorgiaHCA** [comment]
Thanks @katoss great presentation today! I'd love to join. Do you mean the 27th? :)

**Comment by katoss** [comment]
oh yes, I fixed it, thank you :)

**Comment by SaimaButt** [comment]
@katoss i'd love to join please

**Comment by jiraslama** [comment]
I am also looking to join.....

**Comment by jiraslama** [comment]
I am also looking to join.....

**Comment by jiraslama** [comment]
I am also looking to join.....

**Comment by jiraslama** [comment]
I am also looking to join.....

**Comment by jiraslama** [comment]
I am also looking to join.....

**Comment by jiraslama** [comment]
I am also looking to join.....

**Comment by katoss** [comment]
@SaimaButt @jiraslama I invited you to the call :)

**Comment by katoss** [comment]
@GeorgiaHCA @jiraslama @SaimaButt The summary of all user feedback sessions is uploaded here now (in case you would like to have a look before the call): https://github.com/katoss/katoss.github.io/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md 

It will be on the main fork soon, with the next pull request :)

**Comment by katoss** [comment]
Here is the link to the hackmd for the call: https://hackmd.io/@aTJ25MvhRTaerBfH-DluJw/BJsJtbSXv/edit

**Comment by GeorgiaHCA** [comment]
This is a truly wonderful piece of work! Thank you very much. Closing this now as it's complete.
