### ISSUE TITLE
Issue Design: General documentation viewer control

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#318]
### As a 

Designer

### I would like to...

create for the community a wireframe design for the general documentation viewer control that displays documents such as the community conduct or moderation policies

### Because...

community can review the concept and to provide a design for platform prototypes

### Acceptance criteria

Axure updated with the final UI design for the component
A picture/screenshot image of the final UI design of the component held within Axure
Justification of the component design available in Github repository as an md file

### Other relevant documents
Values
Ways of working

### Review owner
Internal development team
Alan Turing

---

## Notes

* Associated pull request: WRITE HERE
* Current status: WRITE HERE

---

**Comment by jiraslama** [comment]
Wireframe for review:
https://c6q95y.axshare.com/#g=1&p=aug_doc_viewer_control__318_d1_list
https://c6q95y.axshare.com/#g=1&p=aug_doc_viewer_control__318_d3_panels

**Comment by SaimaButt** [comment]
@katoss please can we have community feedback on the design that @jiraslama has created. Thanks

**Comment by katoss** [comment]
@SaimaButt I will only be on this project until the end of this month, so I won't be able to do another iteration of user feedback sessions. But I will focus on how you can gather feedback in the future in my presentation on 26th August.

**Comment by jiraslama** [comment]
Viewer updated interactive prototype

Doc Viewer List 
https://15akr7.axshare.com/#g=1&p=doc_viewer_control__318_d1_list

Doc Viewer Panel 
https://15akr7.axshare.com/#g=1&p=doc_viewer_control__318_panels_view

Doc Viewers for community review

**Comment by SaimaButt** [comment]
Development issue created - Issue number 7
