### ISSUE TITLE
Issue Design: Fujitsu wireframe Page Taglines

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#319]
### As a

Designer

### I would like to...

to create for the community a wireframe design for page taglines

### Because...

the community can review the concept and to provide a design for platform prototypes

### Acceptance criteria

Axure updated with the final UI design for the component
A picture/screenshot image of the final UI design of the component held within Axure
Justification of the component design available in Github repository as an md file

### Other relevant documents

Values
Ways of working

### Review owner

Internal development team
Alan Turing

---

## Notes

* Associated pull request: WRITE HERE
* Current status: WRITE HERE

---

**Comment by jiraslama** [comment]
Wireframe for review:
https://c6q95y.axshare.com/#g=1&p=aug_page_taglines__319

**Comment by SaimaButt** [comment]
@katoss  another one for you please to gather community feedback please.

**Comment by SaimaButt** [comment]
Development tasked created - Issue Number 25
