### ISSUE TITLE
Make sure contribution process is really clearly defined

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#32]
One of the things that participants who want to contribute to the project often ask for is a really clear step by step guide to contributing.

We have the [contributing guidelines](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/CONTRIBUTING.md) but they're very focused on GitHub at the moment, so updating those to include contributing to the project itself would be great.

Fine to make a specific page though if that's easier.

**Comment by EllenDevereux** [comment]
@KirstieJane is this still required at this stage in the project?

**Comment by GeorgiaHCA** [comment]
I think that this issue has been superseded by more recent ones on onboarding processes. Should I close this issue now @lottycoupat ?

**Comment by lottycoupat** [comment]
@GeorgiaHCA I think with the onboarding process and roadmap it will cover this issue. So would be happy to close it and ensure it's captured in the other stuff!
