### ISSUE TITLE
Issue Design: Fujitsu wireframe new experience publication moderation component

### ISSUE THREAD

**Issue by fjThomasStanley** [alan-turing-institute/AutisticaCitizenScience#320]
### As a

Designer

### I would like to...

create for the community a component wireframe design for the public approval mechanism of community submitted experiences

### Because...

the community can review the concept and to provide a design for platform prototypes

### Acceptance criteria

Axure updated with the final UI design for the component
A picture/screenshot image of the final UI design of the component held within Axure
Justification of the component design available in Github repository as an md file

### Other relevant documents

Values
Ways of working

### Review owner

Internal development team
Alan Turing
---

## Notes

* Associated pull request: WRITE HERE
* Current status: WRITE HERE

---

**Comment by jiraslama** [comment]
Wireframe for review:
https://c6q95y.axshare.com/#g=1&p=aug_new_experience_publication_moderation_componen
https://c6q95y.axshare.com/#g=1&p=aug_new_experience_publication_moderation_componen_1
https://c6q95y.axshare.com/#g=1&p=aug_new_experience_publication_moderation_componen_2

**Comment by GeorgiaHCA** [comment]
Brilliant! https://github.com/katoss/AutisticaCitizenScience/tree/master/platform-designs/wireframes - please can you add to this folder as well? And maybe it needs some subfolders for different design elements?

**Comment by pgc007** [comment]
A component has been created and added to the component gallery that satisfies this issue.

**Comment by jiraslama** [comment]
Thanks for the update, it would be useful to get some screen grabs of this issue and link / screen grab of the code - many thanks Chris

**Comment by pgc007** [comment]
![mone1](https://user-images.githubusercontent.com/64270473/90021549-557c1380-dca9-11ea-9639-b65f55634d45.png)


[moderationofnewexperiences.txt](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/5063196/moderationofnewexperiences.txt)

The image, mone1.png, shows the component in a browser. The file moderationofnewexperiences.txt is the html file containing the template code.

**Comment by SaimaButt** [comment]
Will create a new issue for the prototype work. The issue itself is complete and requires community feedback from @katoss

**Comment by SaimaButt** [comment]
Development issue created - Issue number 25
