### ISSUE TITLE
Plans for August

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#326]
## Summary

Kirstie and Georgia won't be able to make agile sprint meetings throughout August, so this issue is to plan out that time. It would be great to continue to do the user testing as Katharina is only here during August. A presentation gathering and showcasing all the work would be wonderful at the end of August. 

We were thinking August 26th, with a three-hour slot? We can use the backlog refinement session on the 4th to plan this out! 

* [x] Confirm date, time, and attendees. 
* [x] Invite community members - possibly insight group members, previous participants, and current volunteers. 
* [x] Create agenda
- [ ] Run session and put notes from the session onto GitHub

Thanks everyone! 

🌻

**Comment by katoss** [comment]
Sounds like a good idea! The 26th would work for me :)

**Comment by GeorgiaHCA** [comment]
Brilliant @katoss 🌟

**Comment by GeorgiaHCA** [comment]
Date/Time: 26th August 1pm - 4pm
Attendees: Fujitsu development team, Georgia and Kirstie, invite previous participants (everyone who took part in the focus groups), Emma, James, Andrew, Juliette

**Comment by GeorgiaHCA** [comment]
Agenda: 
* consolidated overview of work 
* showcasing work done in relation to community input

**Comment by SaimaButt** [comment]
Hi @KirstieJane @GeorgiaHCA This sounds like a great plan. @GeorgiaHCA if we can have a catch up so that we are aligned on how we put together the Agenda. I will send a meeting invite across

**Comment by GeorgiaHCA** [comment]
Thanks @SaimaButt - looking forward to catching up :)

**Comment by fjThomasStanley** [comment]
Hi @GeorgiaHCA in relation to the community members who are wishing to present in this session, I was wondering how many members we are expecting and how much time in the 3hr session they require.

**Comment by SaimaButt** [comment]
@GeorgiaHCA  we are working out the agenda for the presentation and would like to understand how much time you will require for the presentation from the autistic collaborators?

**Comment by SaimaButt** [comment]
Hi @GeorgiaHCA @KirstieJane this is our proposed plan of Agenda - please can you take a look and advise if we need to make any changes to the content or time frames? 

**Planned Agenda**
1. Overview of Work: Showcasing work done in relation to community input (Focus groups input), 121 Feedback, Wireframe, Git Repository (Chris - 30 mins) + (Thomas - 15 mins)
2. Process: Agile Methodology, Ceremonies, Project management board (Saima - 15 mins)
3. Work Itself: Build and component based development approach throughout Sprints 1 - 6 (Thomas, George, Chris, Paul - 45mins) 
4. Presentations from autistic collaborators (Katherina 45mins????) 
5. Plans for going forward (Craig-15mins) 
6. Q and A (All - 30mins)

**Comment by katoss** [comment]
Hi @SaimaButt, I will try to do a short presentation in about 30 min max in which I will cover the user tests with the autistic collaborators and the reorganisation of the GitHub repository.

**Comment by SaimaButt** [comment]
Thanks @katoss updated the Agenda comments and times accordingly.

**Comment by KirstieJane** [comment]
Hi @SaimaButt - I'm looking forward to tomorrow!

The schedule doesn't have any breaks in it, what do you think about:

| Time | Topic | Presenter |
| ----- | ------ | ----------- |
| 13:00 | Welcome, code of conduct, introductions | TBD - can be Kirstie if you'd like |
| 13:10 | Overview of work: Showcasing work done in relation to community input (Focus groups input), 121 Feedback, Wireframe, Git Repository | Chris & Thomas |
| 13:50 | Process: Agile Methodology, Ceremonies, Project management board | Saima |
| 14:00 | :coffee: Comfort break | |
| 14:10 | Work Itself: Build and component based development approach throughout Sprints 1 - 6 | Thomas, George, Chris, Paul |
| 14:35 | User testing & GitHub reorganisation | Katherina |
| 15:00 | ☕ Comfort break |
| 15:10 | Plans for going forward | Craig |
| 15:25 |  Q and A | All - 30mins |

**Comment by SaimaButt** [comment]
Perfect @KirstieJane

**Comment by SaimaButt** [comment]
@KirstieJane  please can we swap the 13:10 with the 13:50 please
