### ISSUE TITLE
Error in GitHub pages build 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#329]
## Summary

Having merged a PR with sprint documentation, I get the following error: 

"The tag trans on line 62 in project-management/Technical is not a recognized Liquid tag."

I wonder if this is to do with the folder not following the format "technical-docs"? but suspect it's more complex.

## Suggestions for tasks that can fix this issue

I'm going to work on Katharina's fork with the redesigned repo, and move the reports there. 

## Who can help

Anyone with tech and GitHub knowledge/skills. If you have a moment @jhlink, @MaxwellRiess, or anyone else who has some ideas how to fix this, I'd be really grateful got some help! 🌟

**Comment by jhlink** [comment]
Hey, @GeorgiaHCA . Happy to help.

Could you share the PR # and perhaps the branch name where the error occurs?

**Comment by GeorgiaHCA** [comment]
Thanks so much @jhlink - it is pr #315 (now merged annd closed) -  https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/315
