### ISSUE TITLE
Serve OH original demo and make it easy for folks to give feedback on it

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#33]
While @gedankenstuecke was visiting the Turing in July, he and @GeorgiaHCA made a little demo of the platform that integrates nicely into Open Humans: https://github.com/gedankenstuecke/autistica-filemanagement-demo

We need to make this easy to interact with and give feedback on.

Some ideas:

- [ ] Serve the website using netlify so folks can interact with it (make sure that we the researchers have no access to the input data)
- [ ] Add link to that website from README, ghpages website from this repo
- [ ] Add link to google form to demo website to make it easy to see how to feedback thoughts and suggestions

**Comment by gedankenstuecke** [comment]
The demo can't be deployed to Netlify I think, as it's not just a static website but has it's own database and is not just a static website. But the demo project can be deployed to a free `Heroku` project pretty easily. I'd be happy to help with that!

**Comment by KirstieJane** [comment]
Thank you @gedankenstuecke!! That would be amazing.

What do you think of moving the code to a folder in the main citizen science repo now that it’s public? Or would it be more sensible to keep the code etc in a separate repo?

**Comment by gedankenstuecke** [comment]
For the deployment to Heroku it's easier if it remains its own repo I think as it expects a certain folder structure. But we could transfer that repo to your own Organization.

For the deployment to Heroku: Do you have an account there already?

**Comment by SuziQpid** [comment]
Finally found a user friendly interface. As most l.T. challenged member of Citizen Science but keen to stay in touch, may l remind everyone that not every uses main frame computers or laptops. I’m typing on an iPad mini, and to be irritatingly non synced except via Google, an Android phone. Autistic participants in the move and with limited digital resources need to be able to create a github account and get stuck straight in. I did that, thought ld be super keen and go to the gitter chat room only to discover after adding my ‘ repository’ ( horrible word that feels like some kind of sanitised ‘dump ‘) that l couldn’t type in unless l could raise a keyboard to do control/ slash stuff. Guess what couldn’t find a way of doing that. Returned to email and decided to follow straight forward github link. I think for the less tech savvy you should clarify which platforms will work best with which types of operating systems iOS, Android etc. There are too many links to too many interfaces. If you say who will be monitoring or doing the admin on the github, whether responses will be instant, or say take 24/ 48 hrs we will know what to expect. This Autistic Geordie needs to know lm not gonna get ‘ hetup ‘ if there’s digital silence. What lm resdding above Heroku etc is a foreign language that l can’t ever hope to speak. I wonder if others in lnsight focus group Kirstie are also a few light years behind in this tech speak. I can follow a little of your first suggestions about demos and would be more than happy to be a digital guinea pig. I helped test the user friendliness of the  Peoplefirst website before it was launched.

**Comment by KirstieJane** [comment]
Thank you @SuziQpid!! I really appreciate your comments. There are quite a lot of great actions we can take to make it easier for folks like you in the future. I've copied your comment to a new issue (a task for the project to complete) here: #36.

**Comment by SuziQpid** [comment]
You're very welcome !

Warm regards

Sue.

PS my disabled co production implementation group in LBHF want to watch a
presentation about this important research on ambient environs work. Is
there a particular video or link l can share with them.

**Comment by KirstieJane** [comment]
Hi @SuziQpid! So sorry I missed this question. There are these two links that give a very brief overview. We don't have anything more detailed yet.

* https://youtu.be/p9tfhgVUuQE
* https://youtu.be/rP1S8ip4VVE

**Comment by KirstieJane** [comment]
@gedankenstuecke - sorry for the slow reply. It would be great if we could transfer the demo to the alan-turing-institute organisation.

@GeorgiaHCA - please could you make a Heroku account (https://signup.heroku.com/). I think that makes more sense than me being the account holder.

**Comment by gedankenstuecke** [comment]
@KirstieJane I tried to do the transfer, but I can't transfer the ownership as I lack the permissions to create repos in the `alan-turing-institute` organization. Maybe you can just make a fork from my repo? 

For heroku: You can create teams in Heroku and/or invite other people to give them also access to the app deployment, that way we can all control it.

**Comment by KirstieJane** [comment]
Ah, interesting. How about this - can you add me as an admin to your repo and I'll see if I can transfer ownership? I just recently got into a bit of a mess with not being able to search a repo because it was a fork so I'd rather keep this work as the main repo.

I'll make an account on Heroku now 😄

**Comment by GeorgiaHCA** [comment]
I made a Heroku account :)

**Comment by gedankenstuecke** [comment]
> Ah, interesting. How about this - can you add me as an admin to your repo and I'll see if I can transfer ownership? I just recently got into a bit of a mess with not being able to search a repo because it was a fork so I'd rather keep this work as the main repo.

Yes, that works, you're already invited to be a collaborator on the repo, but I'm not sure you've already accepted it?

**Comment by gedankenstuecke** [comment]
So, I requested a transfer of the repo to @KirstieJane, then Kirstie can transfer it to the turing from there.

For heroku: My heroku account runs under "bastian@openhumans.org" :)

**Comment by KirstieJane** [comment]
Oooooh - I'm sorry about missing that invite!

I have the repository now: https://github.com/alan-turing-institute/autistica-filemanagement-demo :muscle:

**Comment by EllenDevereux** [comment]
@gedankenstuecke are we ready to close this issue

**Comment by GeorgiaHCA** [comment]
Closing this issue now as we have a new version to be deployed: https://github.com/alan-turing-institute/AutSPACEs/issues/210
