### ISSUE TITLE
Get app running on local machine

### ISSUE THREAD

**Issue by danb-bh** [alan-turing-institute/AutisticaCitizenScience#334]
## Requirements
- [x] Add docker files to source control
- [x] Add instructions to README

## Extra freebies
- [x] Tidy up `.gitignore`

**Comment by SaimaButt** [comment]
Awaiting for permissions to be assigned to the repository by @GeorgiaHCA @KirstieJane

**Comment by danb-bh** [comment]
Note that the permissions are needed on the https://github.com/alan-turing-institute/AutisticaPlatformPrototype repo for e.g. @fjThomasStanley to be able to merge PR https://github.com/alan-turing-institute/AutisticaPlatformPrototype/pull/5

**Comment by GeorgiaHCA** [comment]
Thanks for pointing this out @danb-bh and thanks for fixing @KirstieJane  - should be sorted now!
