### ISSUE TITLE
Have Kirsty’s YouTube video right at the start.

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#336]
It explains the project really well. A button linking you to detailed information on the project. A button that says ‘share my experience’.

**Comment by GeorgiaHCA** [comment]
This is based on feedback from @Angelsaur

I've now added it at the beginning of the main README in the redesign: https://github.com/katoss/katoss.github.io/blob/master/README.md

**Comment by GeorgiaHCA** [comment]
There are now options for more detailed information in the get-involved section and also links to specific kinds of information in the contents. 

There is no button on this website which says "share my experience" as that will be a feature of the product when it has been built but not in the co-design phase. I've included some additional clarifying sentences.

Would you be able to take a look @Angelsaur and let me know what you think?

**Comment by Angelsaur** [comment]
Hi,

This is much clearer and easy to follow. Thanks so much for taking on board my advice!

________________________________

**Comment by GeorgiaHCA** [comment]
Fantastic @Angelsaur - so glad you like it! Closing this issue now we've incorporate your preferred changes. Feel free to take a look at the issues or make more suggestions if you've like to be involved more 😸
