### ISSUE TITLE
User testing handover

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#358]
## Summary

@katoss has done some awesome work designing, runnning, annd analysing user testing sessions, but she could only join us for a limited time. We need to make sure that we handover and resource the user testing process, so that her wonderful work continues. 

- [x] @katoss to create handover notes
- [x] Fujitsu/Turing team to identify person or people to run/write up tests going forwards
- [x] Ensure means of sustainable/diverse user testing recruitment

## Date Due by

* we have a lot of issues ready for testing, so sorting this is a priority 
* important this is built into the sprints and ready for the next release of the prototype.

**Comment by SaimaButt** [comment]
We have set a plan for Paul Mitchell to go through testing on a weekly basis. He will work three hours a week and go through the prototype issues on the development board. Paul will do the acceptance testing. Paul has access to the development board. @fjThomasStanley  please can you give him access to the environment in git.

A meeting is set up for Monday to go through this with Paul
FYI @jiraslama

**Comment by jiraslama** [comment]
Testing methods shared with Paul Mitchell who has now starting testing from a user and code perspective.
