### ISSUE TITLE
Video summary of User feedback session as a stand alone video

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#362]
As a community member
I want to be able to see a video summary of the User feedback
So that I can see the development work and the user feedback separately

Acceptance Criteria
- Create a YouTube video
- Video content based on the feedback received fro the summary of each section from Katherina
- Requires approval from Katherina

**Comment by jiraslama** [comment]
Video Summary of Sprint 6 User Feedback Sessions 

https://youtu.be/kRBXYbqVbgE

**Comment by GeorgiaHCA** [comment]
Thanks for creating this video! It looks really clear @jiraslama ⭐ @katoss will add it to the readme of the user feedback, and then this issue is ready to close.

**Comment by GeorgiaHCA** [comment]
@katoss has added the video to the readme, so closing this issue now. Good work everyone 🎉

**Comment by jiraslama** [comment]
Further Presentation Materials from the 26082020 as documentation of process - delivery 

Autistica CSP
Sprints 1 - 8 
Presentation of Process
26082020
[Autistica Agile Delivery Approach.pptx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/5186827/Autistica.Agile.Delivery.Approach.pptx)
[Autistica Byte Scrum Agile Delivery Approach_1.pptx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/5186829/Autistica.Byte.Scrum.Agile.Delivery.Approach_1.pptx)
[Autistica Citizen Science update (August 2020).pptx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/5186830/Autistica.Citizen.Science.update.August.2020.pptx)

Videos 

Autistica CSP
Sprints 1 - 8 
Presentation of Development Work 
26082020
https://youtu.be/MY9nLqf8dtI


Autistica CSP
Sprints 1 - 8 
Presentation of Design
26082020
https://youtu.be/pX66xqRZYW4
