### ISSUE TITLE
Feedback on the GitHub reorganisation

### ISSUE THREAD

**Issue by katoss** [alan-turing-institute/AutisticaCitizenScience#363]
## Context
@GeorgiaHCA & @katoss have reorganised this GitHub repository's folder structure and updated readmes to make everything easier to understand for new users.

## Task
It would be great to get feedback on the current form of the GitHub repository (organisation of the folders, content, readmes...). Is it easy to understand? Do you find the information you need? Is something missing?
This is a great task for **new contributors**!

## How to give feedback
Just comment under this issue :) We are happy for any kind of feedback on the structure and contents of this GitHub repository!

**Comment by Angelsaur** [comment]
The website is now much clearer and it’s easier to see the aims and values of the project. It’s also clearer now that what you’re looking for is advice on design at the moment and autistic experiences later once it’s up and running. 
Thank you for listening to my input.

**Comment by GeorgiaHCA** [comment]
That's good to hear @Angelsaur - thanks so much for sharing your feedback, it makes a big difference!
