### ISSUE TITLE
Support for calming emotional state

### ISSUE THREAD

**Issue by osw** [alan-turing-institute/AutisticaCitizenScience#371]
# Overview
*As a platform user
I want to be able to access calming resources
So that I am in a good frame of mind to record my experiences*

## Idea
COVID-19 is creating additional stress for people. The idea is to have access to videos that may help calm the user

# Out of scope
* Create the videos themselves

# To be confirmed
* Should the app host videos, or have an area to link to videos hosted elsewhere?

**Comment by GeorgiaHCA** [comment]
This user story is based on recommendations from an Autistic commnuity member given at an open call to showcase work on the project.

The original notes fom that meeting which this user story is taken and adapted from are here: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/workshops/developer-showcase-August2020.md

**Comment by SaimaButt** [comment]
Investigate other organisational links or resources that we can add into our app
