### ISSUE TITLE
Moderation: Focus Groups and Code of Conduct 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#385]
## Summary

This issue is about arranging a focus group to co-design a code of conduct for the use of the platform. 

## Why
* This comes from multiple focus groups in which we had lots of suggestions and recommendations that a code of conduct would be useful. Caroline Hearst, an autistic autism advocate, also suggested a code of conduct would be essential
*  It is also part of best open source practise following the expertise of KW 

## Date Due by

It would be great to arrange this for early November, and aim to have the first version of the code of conduct written before the end of 2020 so it's in place for the launch of the prototype platform. 

## Suggestions for tasks that can fix this issue

1. [x] Find other good examples of code's of conduct for moderation 
- [x] Create an initial (rough) scaffold including all the essentials and basics of general codes of conduct before the more detailed discussion takes place
- [x] Work out budget and where resources are coming from 
1. [x] Decide who to invite, what roughly should be included, and what platform it should take place on 
1. [x] Create an agenda, arrange a time
1. [x] Send out invites, including consent forms, payment forms, instructions etc. 
1. [ ] Run session and take notes for code of conduct rules
1. [ ] Incorporate into scaffold-structure
- [ ]  Circulate completed code of conduct to previous participants to make sure captures their views
- [ ] Respond to second set of suggestions, and publish code of conduct on GitHub for community review 

## Who can help

Anyone can help by offering suggestions which would fix any of the above tasks! In particular:
Autistica could help draw up invites 
Previous participants could help 
Volunteers could help

**Comment by GeorgiaHCA** [comment]
1. [ ] Find other good examples of code's of conduct for moderation
* AutAngels has a code of conduct which was created by and for autistic people, and which we have permission to take and adapt for out own study: https://www.autangel.org.uk/wp-content/uploads/2020/03/1904_autangel_code_of_conduct.pdf
- [ ] Create an initial (rough) scaffold including all the essentials and basics of general codes of conduct before the more detailed discussion takes place:
* This will include basic principles for running a welcoming community as well as suggestions from previous focus groups (which can be reviewed)
- [ ] Work out budget and where resources are coming from
* I would suggest Autistica and using Involve guidelines but would have to check this out (unless there is funding available elsewhere?)
1. [ ] Decide who to invite, what roughly should be included, and what platform it should take place on 
* It's vital we include a diverse group, including BAME people. a mix of ages, and both carers and autistic people. I suggest Zoom for the platform given the current Covid situation, as this will allow breakout rooms for smaller discussions (and we can include a writing only and speaking only options for people according to their different preferences). 
* We have a list of "who's not in the room" suggested by project participants in focus groups - this could be a god thing to look at when deciding who to invite and how to engage. 
1. [ ] Create an agenda, arrange a time
* For the agenda I suggest we include:
 * welcome/ice-breaker/form filling
 * presentation on codes of conduct/defining the problem
 * presentation of feedback from previous focus groups and what emerged 
 * some focus on the question of reporting on behalf of others
* lots of time for rule-writing - what should and shouldn't we moderate for
* what next? code of conduct as a living document, not set in stone
1. [ ] Send out invites, including consent forms, payment forms, instructions etc. 
* (these are detailed in the study protocol for running in-person sessions)
1. [ ] Run session and take notes for code of conduct rules
* (Using HackMd?) May also need to record or provide assistance for those who would prefer not to write 
1. [ ] Incorporate into scaffold-structure
* Add the changes to the existing scaffold (the idea of drawing upon existing models rather than completely "reinventing the wheel" was brought up a few times in focvus groups, so the "scaffold" idea comes from autistic participants and is designed so that their time is requested with efficiency in mind)
- [ ]  Circulate completed code of conduct to previous participants to make sure captures their views
* This will include allowing time for both reading and commenting 
- [ ] Respond to second set of suggestions, and publish code of conduct on GitHub for community review
* (it may also be useful to do some user testing with scenarios to see if people interpret the code of conduct in similar ways, and if they think it's fair)

**Comment by GeorgiaHCA** [comment]
# Agenda

10:00 - 10:30 Welcome/ice-breaker/form-filling
10:30 - 11:00 presentation of codes of conduct and previous feedback
11:00 - 11:15 BREAK
11:15 - 11:45 norm setting
11:45 - 12:15 guidelines for reporting on behalf of others
12:15 - 12:30 Plans for after lunch
12:30 - 13:15 LUNCH
13-15 - 14-00 breakout sessions
14:00 - 14:15 BREAk
14:15 - 15:00 breakout sessions
15:00 - 15:15 BREAK
15:15 - 16:00 Closing discussion and next steps

**Comment by GeorgiaHCA** [comment]
Proposed date Monday 30th November

**Comment by GeorgiaHCA** [comment]
Updated Agenda here: https://hackmd.io/9OydEFQ_RwWb5P70dZlxxw#%F0%9F%98%8C-Part-5-Reflections-and-next-steps---15-minutes

**Comment by lottycoupat** [comment]
@GeorgiaHCA is this still needed when we have issue #432 and the meet-ups are up and running?

**Comment by GeorgiaHCA** [comment]
Hi @lottycoupat - yes, I tihnk we can close this now, as the discussion sessions ran a different course. Issues relating to the code of conduct can be added as we plan it with Susanna and James
