### ISSUE TITLE
Building out of acceptance criteria for issues from Prototype Set - Ready for Testing

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#399]
Building out of acceptance criteria for issues from Prototype Set - Ready for Testing https://github.com/alan-turing-institute/AutisticaPlatformPrototype/projects/1

**Comment by jiraslama** [comment]
[Acceptance-Criteria.pdf](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/5475184/Acceptance-Criteria.pdf)
Overarching Requirements  - Conditions

**Comment by GeorgiaHCA** [comment]
The acceptance criteria will evolve with each iteration. 
Building on Chris' work, the latest version is here: https://github.com/GeorgiaHCA/AutSPACEs/blob/main/platform-design/requirements-list.md Closing this issue now.
