### ISSUE TITLE
Name the Platform

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#4]
This is something to workshop with the community, so there's no rush in naming the project right now!

But here's an issue to capture any ideas and discussion as we go along, and to make sure we don't forget 😸

**Comment by JamesSCTJ** [comment]
Kirstie Jane/Georgia HCA. Can I make a suggestion? **'Vision'.**

I think Vision encapsulates what the project is about in both the practical sense but also in-terms of the vales that the project stands for (understanding how neurodiverse  people interact with both the physical and social environments, in-essence how they see the world); it's about helping the rest of us better understand these experiences, essentially opening our eyes to different ways of interacting with the world. 

It's also short, snappy, memorable and relevant (without over-describing) so I think it meets theories in-terms of what makes a good product name.

Just a thought to get the conversation started!

**Comment by GeorgiaHCA** [comment]
Let's put this out in July's newsletter?

**Comment by JamesSCTJ** [comment]
I definitely think so!

James

**Comment by GeorgiaHCA** [comment]
The platform has now been named - AutSPACEs (an acronym for Sensory - Processing for Accesible Community - Environments). Thanks everyone who helped ! 🌟
