### ISSUE TITLE
Co-working subgroups

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#411]
## Summary

Create working groups for collaborators interested in working on shared areas of the citizen science platform. 

## Date Due by

Tusday 16th Feb - in time for the next Thursday co-working session. 

## Details

The following areeas of interest emerged

* Web development and tech support 
* Research 
* Comms and community engagement 

## Suggestions for tasks that can fix this issue

Scope and clarify groups
Add othre interested members
Structure actions and formalise milesetones

If you are interested in subgroups let us know!

**Comment by lottycoupat** [comment]
Similar to issue #427 @GeorgiaHCA

**Comment by GeorgiaHCA** [comment]
Yep, agreed! We've moved on since this issue creation. Happy to close this @lottycoupat
