### ISSUE TITLE
Prepare University of Tennessee science and ethics conference 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#413]
## Summary

Our abstract was accepted! Yay! We will use this conference as an opportunity to engage across disciplines in the ethics of participation in scientific rsearch. 

Abstract here: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/applications/PGSAUT-abstract.md 

## Date Due by

The event will be held virtually March 13–14, 2021, so:
Have a draft ready by March 1st

## Details

More info can be found here: https://philosophy.utk.edu/newsitem.php?news_id=1931  
Meeting 09/02/2020 to discuss further 

## Who can help

This task is being done by Ismael, Georgia and Susanna, but suggestions are welcome. When finished, the presentation will be uploaded to this repo for review.

**Comment by GeorgiaHCA** [comment]
Tagging you @MaxwellRiess as I know philosophy is a particular strength of yours, so if you have views/ideas to share or you have some time to review the presentation that would be great!

**Comment by lottycoupat** [comment]
@GeorgiaHCA can we close this?

**Comment by GeorgiaHCA** [comment]
Thanks @lottycoupat - yes, the link to Zenodo is now in the project communications folder, so I'll close this now
