### ISSUE TITLE
Focus Group Questions

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#42]
We have three focus group sessions coming up to discuss the project. What would be the best structure for the sessions/questions to ask?

**Comment by GeorgiaHCA** [comment]
Ideas for questions to ask: 

OS: 

What intrigued you about the project? 
What's your relationship/connection to autism or the project's issues? 
What do you expect from this session? 
Do you require any additional support? 
What's your preferred style of working within a group? Written, verbal, images? - Catering to accessibility
Incorporate a quiet space if it gets too much
Do people have mobility impairments? Be prepared for this.
No more than 2-3 questions per turn (break up session) - if people have extra questions or suggestions  put in a comment box  so they can still be responded to
In case people have difficulties, e.g. anxiety, have someone to assist/make sure they get included. 
Make clear that people can't make their own recordings. 
Booklet or material about what to expect. 

GA:
What do you expect from the platform? 
How would you like to contribute? 
Any barriers to contributing? 
Demonstrate any prototypes or wireframes we have available (or ideas)

**Comment by GeorgiaHCA** [comment]
We now have a third focus group on Friday to prepare for - and agreed a new agenda would be better.

**Comment by GeorgiaHCA** [comment]
[4oct Focus Group Schedule.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/3678700/4oct.Focus.Group.Schedule.docx)

**Comment by EllenDevereux** [comment]
Schedules & questions have been uploaded.
