### ISSUE TITLE
Create onboarding process

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#420]
## Summary

Add a robot? 
Have a ladder where you can add your level

**Comment by GeorgiaHCA** [comment]
AR Plugin that sits on top of repo to guide

**Comment by lottycoupat** [comment]
Currently working on an Onboarding pack as a PPT and looking to create some videos to go with it. Also as an onboarding process to have 1:1s with new members ahead of their first "meet-up" so that they arrive knowing the background of the project.
