### ISSUE TITLE
BUG Broken links

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/AutisticaCitizenScience#421]
## Summary
There are broken links on this [page ](https://alan-turing-institute.github.io/AutisticaCitizenScience/project-management/). Can we please fix the, and have them point to the correct files. 

## Date Due by

ASAP 🐛 

## Suggestions for tasks that can fix this issue

* [x] check which links go to a 404
* [x] find the file they're meant to direct to
* [x] replace the broken link with the correct one
* [x] test (the files may be in a private repo which is why they 404) while logged out of github account 
* [x] QA test across Chrome, Sarafi, and Firefox

## Who can help
Anyone who has access to the repo and can find the files.

**Comment by GeorgiaHCA** [comment]
All links fixed in landing page!

**Comment by GeorgiaHCA** [comment]
All links fixed in .github folder

**Comment by GeorgiaHCA** [comment]
everything fixed in the 'applications' folder

**Comment by GeorgiaHCA** [comment]
Lots of links to fix here: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/focus-groups/creation-summary-documents.md

**Comment by GeorgiaHCA** [comment]
Links fixed in community-recommendations folder

**Comment by GeorgiaHCA** [comment]
There are a lot of broken links throughout the site because of a few layers of Repo reorganisation: 

I've looked through:
The main README
applications
community recommendations

the rest are still to do!

**Comment by GeorgiaHCA** [comment]
Links fixed for landing page (README), so opening a new issue for other pages! Thanks for flagging this @BrainonSilicon 🌟 ⭐ 🌟
