### ISSUE TITLE
Create user experiences

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#44]
Quote from @fjThomasStanley in Gitter (emphasis from @KirstieJane):

> The Fujitsu team are still very much in the project initiation phase and therefore we will still need to decide and agree on how we would like to receive user requirements, however I think we would like to use a **standardised Agile User Story format**. I have created a potential example format to be discussed with the team on the [Fujtsu fork](https://github.com/fjAutisticaCitizenScience/AutisticaCitizenScience/issues) of the AutisticaCitizenScience repository as a template for a new issue. I will raise the point about user requirements format in our next meeting next week with the team.

So no action at this time.

**Comment by EllenDevereux** [comment]
@KirstieJane @fjThomasStanley please can you confirm that this has been covered in more recent issues.
