### ISSUE TITLE
May Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#443]
## Summary

Every month we send out a newsletter for all members who hav signed up. to our mailing list. This contains project updates, calls to action, and an intreview with a community member.

## Date Due by

31st May 2021

## Suggestions for tasks that can fix this issue

- [ ] Write newsletter, including updates for past month
- [ ] Include interview with a community member
- [ ] Complete in a HackMD as a markdown document 
- [ ] Put into html and put a copy edited version into a draft on tinyletter
- [ ] Get this checked over by community member
- [ ] Add completed newsletter to repo in a PR 

## Who can help

Anyone of all levels is welcome to help either by being interviwed, co-editing, or nominating somoene for an interview .

**Comment by GeorgiaHCA** [comment]
Hiya @lottycoupat - sounds like you're really on top of this, but here's an issue for the monthly newsletter with a checklist in case it helps. Also you get to complete an issue which is satisfying ;)

**Comment by lottycoupat** [comment]
@GeorgiaHCA I have drafted a newsletter in a github branch! But will add it to the drafts within tinyletter and add some more stuff to it. Can you attach a branch to an issue or only a pull request?

**Comment by GeorgiaHCA** [comment]
Amazing! When you're ready, you can turn your branch into a pull request. This just means you are asking us to add the changes you've made on your branch to the main one. 
Here are the steps:

**Comment by GeorgiaHCA** [comment]
<img width="1127" alt="Screenshot 2021-05-07 at 16 21 58" src="https://user-images.githubusercontent.com/46889966/117472260-9e1edf80-af50-11eb-9fd6-91f9e794a49a.png">

**Comment by GeorgiaHCA** [comment]
Go to the branch where you made the changes

**Comment by GeorgiaHCA** [comment]
<img width="532" alt="Screenshot 2021-05-07 at 16 25 17" src="https://user-images.githubusercontent.com/46889966/117472499-d9b9a980-af50-11eb-8ab7-868ff4385a91.png">

**Comment by GeorgiaHCA** [comment]
Then you can click "Pull Request" when you're ready, or you can click "compare" first to see the difference between your branch and the main branch (these are the on the grey bar under where the big green code button is)

**Comment by GeorgiaHCA** [comment]
<img width="1310" alt="Screenshot 2021-05-07 at 16 27 35" src="https://user-images.githubusercontent.com/46889966/117472825-35843280-af51-11eb-9e6b-bdfae9180b64.png">

**Comment by GeorgiaHCA** [comment]
Then you get a screen like this! You add a name for the change your making, and put in comments in the main box which makes it easy for reviewers to know what they need to look at.

You can also choose who you want to review by using the menu on the right hand side.
