### ISSUE TITLE
Add Lotty's objectives to this repository

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#448]
## Summary

@lottycoupat is seconded to the Turing Institute for 6 months to work as the AutSPACEs community manager.
We should add her objectives to this repository to make clear what she's working on and to monitor progress 😄 

## Date Due by

10 May

## Details

* This might end up being the first step in a process to capture roles and responsibilities across the project... have that in mind for where _others_ will add their objectives too etc!

## Who can help

@lottycoupat can do this

But maybe with help from @malvikasharan who can show Lotty how we capture contributions in the Turing Way 👾

**Comment by lottycoupat** [comment]
Have added my objectives and attached the relevant pull request to this issue. 

@malvikasharan Do you have time this week or next to discuss how you capture contributions in the Turing Way? 😄
