### ISSUE TITLE
Create plan for fortnightly reporting

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#452]
## Summary
Plan of what to be included and who needs to be involved for the fortnightly reporting of the AutSPACEs project. 

## Date Due by

COP 07/05/21

## Suggestions for tasks that can fix this issue

Define:
* When fortnightly reporting will be
* Who needs to be involved
* What information is needed 

## Who can help
Those in project team.

**Comment by GeorgiaHCA** [comment]
Beautiful issue Lotty! 

I've made a HackMD to capture the plan here: https://hackmd.io/hUaggfHuSlO2afEpDlCxyg so we can asily upload it to GitHub aftrwards

**Comment by GeorgiaHCA** [comment]
Hiya @lottycoupat - I reckon we could close tihs issue now as we seem to have a format that works? :)

**Comment by lottycoupat** [comment]
agreed @GeorgiaHCA 👍
