### ISSUE TITLE
Define skills needed for contributing to certain areas of the project

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#453]
## Summary
Defining the skills needed for contributing to certain areas of the project. Specifically, for platform development where skills needed are very technical.

## Date Due by 11/05/21

**Comment by GeorgiaHCA** [comment]
The platform is built using Django to integrate the Python-based backend with an html interface. I would think that the most essential knowledge would be the ability to use GitHub.

In terms of joining in with development, this (step-by-step)[https://github.com/alan-turing-institute/AutSPACEs/blob/main/dev_readme.md] is probably useful to share? 

They would also need to know about Open Humans, and how the backend works.

**Comment by jhlink** [comment]
Yes, absolutely @GeorgiaHCA ! Currently on leave, but I'm happy to help as soon as I'm able!!

**Comment by GeorgiaHCA** [comment]
Of course, enjoy @jhlink !!

**Comment by lottycoupat** [comment]
@GeorgiaHCA I sent James a message after our meeting regarding the skills needed. He has sent me some really good info on skills needed (thanks @jhlink) that I have added to a github branch and working from there!

Enjoy your leave @jhlink
