### ISSUE TITLE
Roadmap ideas

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#462]
## Summary

This issue is where w can work openly togeether to add milestones and issues which should be part of the overall roadmap. Then @lottycoupat can curate these into a structured roadmap on a separate issue. 

All core researchers
**Write a comment under this issue to add things needed for the roadmap or to ask questions/clarify** 

This Roadmap working doc for the project as a whole links to this one for platform development in particular: https://github.com/alan-turing-institute/AutSPACEs/issues/95

**Comment by BrainonSilicon** [comment]
Thanks for opening this @GeorgiaHCA! Would it be a good idea to have this be titled "Project ideas" and then have a roadmap tag on it (so as not to confuse it with the core roadmap issue)

**Comment by GeorgiaHCA** [comment]
Here are some high level milestones I think it would be useful to have in the roadmap (obviously lots more detail needed):

* Build platform
* Launch platform
* Diversity/accessibility - engagement and inclusion
* Future funding (for project sustainability) - pivot to co-occuring conditions
* Grow community and create onboarding process/make repos ready for newcomers
* Publish paper on project  
* Design and implement moderation process
* Collect dataset using platform which is useful for research 
* Establish pathways/routes to impact (e.g. connect people who can make changes based on data)

**Comment by GeorgiaHCA** [comment]
Heya - this is an initial sketch of what I think major milestons are from my perspective. I realise these are insanely broad categories! I'd imagine each would be broken down into subgroups (which could be identiifided by labels), and individual issues. What do you think @lottycoupat, @KirstieJane? 

I've suggested some more specific ones for the platform build here: https://github.com/alan-turing-institute/AutSPACEs/issues/95.

**Comment by GeorgiaHCA** [comment]
Another one might be making sure there is a much clearer link from community input and discussion to outputs

**Comment by lottycoupat** [comment]
**INITAL BRAINSTORM - I think bulking each of these out with what tasks need to be done for each would be fab:**
Build platform
Launch platform
Diversity/accessibility - engagement and inclusion
- Define accessibility requirements
- User testing to ensure accessibility WCAG 
Future funding (for project sustainability) - pivot to co-occurring conditions
- List of funding applications
Grow community and create onboarding process/make repos ready for newcomers
- Map out onboarding process
- Create onboarding pack
- Establish route for newcomers to come to community manager
- 1:1
- Establish participation model and strategy
- Tidy repositories to ensure up to date information and correct links
- Communication plan
Publish paper(s) on project
- Chapter writing
- Research on surrounding papers and topics
Design and implement moderation process
- Map out tasks which need decisions and dependencies
- Write guidelines for moderators
- Decide how many moderators are needed
- Map out escalation route for undecided stories
- Assign moderators
Collect dataset using platform which is useful for research
- Where will this go and how will it be shared?
- Share/Engagement with community? 
Establish pathways/routes to impact (e.g. connect people who can make changes based on data)

**Comment by GeorgiaHCA** [comment]
This is awsome work @lottycoupat ! 🌟 🤩 🚀

**Comment by GeorgiaHCA** [comment]
R.e. defining accssibility requirements for the platform, I've taken the ones from GDS which government sites need to pass to ensure they're accessible and put them all into issues labelled "accessibility" on the AutSPACEs repository

**Comment by GeorgiaHCA** [comment]
Some other issues related to accessibility:

#14 

#18 

#24 (these were changes recommend by an autism researcher for the Google form survey - which we couldn't asily change because of ethics, but can bee used to modify consent forms, google survey, informing other stuff going forwards)

#54 

#100 

#106 

#409 

#417

**Comment by GeorgiaHCA** [comment]
https://github.com/alan-turing-institute/AutSPACEs/issues/32 - this issue on AutSPACEs is also related (not sure how you would like to record across the two repos?)

**Comment by GeorgiaHCA** [comment]
List of organisations it could be worth contacting r.e. diversity, inclusion, and accessibility:

## List of organisations to contact:
* Autistic communities: 
	* [AutAngel](https://www.autangel.org.uk/community/)
	* [AutismVoice](https://www.autismvoice.org.uk/)
	* [Ambitious About Autism](https://www.autism-alliance.org.uk/ambitious-about-autism/)
	* [Autistic self-advocacy network](https://autisticadvocacy.org/)
	* [Aspens](https://www.aspens.org.uk/our-mission)
	* [Centre for BME health](https://centreforbmehealth.org.uk/resources/toolkits/)

**Comment by GeorgiaHCA** [comment]
Here's a link to a community involvment stratgy I was working on with @JamesSCTJ https://hackmd.io/tfZgUFHDQTqLYh-Ys9K-iw
