### ISSUE TITLE
Create guidelines for moderators re the moderation process

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#473]
## Summary

We need to create guidance for moderators so that they understand what they need to do for each story. 

## Date Due by

End of June. 

## Details

Create and draft guidance. 

## Suggestions for tasks that can fix this issue

* [ ] Define moderation
* [ ] Create guidance
* [ ] Review of the first draft 
* [ ] Finalise the guidance

## Who can help

Anyone who is interested in the moderation process.

**Comment by lottycoupat** [comment]
@GeorgiaHCA I have created this issue to kick start process.

**Comment by GeorgiaHCA** [comment]
We need something that clearly explains the process to creating the summary documents. @JamesSCTJ already helped create these for the focus group summaries

We should adapt these for the moderation co-creation session.

**Comment by GeorgiaHCA** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/focus-groups/creation-summary-documents.md

**Comment by lottycoupat** [comment]
@skfantoni @JamesSCTJ 

Guideline on the use of quotes in stories. Based on decision - quoting offence language should be okay.
