### ISSUE TITLE
Project booth at British Library National Inclusion Week event

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#49]
@GeorgiaHCA is going to be presenting the project at the British Library national inclusion week event on **Thursday 26 September** from 12noon to 3pm.

This issue is to track some of the tasks that we need to complete to prepare for that event.

- [x] Little blurb about the booth - 3-5 sentences
- [x] Make some postcards with key information about the project and how to get involved
- [x] Ask an autistic collaborator to join in, even if just for part of the event?
  * This is a bit of a tough one because presumably its quite a big ask - it will likely be noisy and busy... But anyone reading this who would like to be involved would be extremely welcome, and maybe Bethan can recommend some members from the Insight group to come along? Or an (autistic?) Autistica staff member?
- [x] Get some useful materials from Autistica to hand out
- [x] Get some promotional materials from the Turing to hand out
- [x] Make sure to have laptop to show how to navigate github, the google form and the heroku app. Note that both need internet access to work, so be prepared to discuss in the abstract if the wifi goes down.

Anything else I haven't thought of?

**Comment by gedankenstuecke** [comment]
Just as a heads-up: the demo app won’t work without internet connection, even if running locally. As all the data is mainly stored on Open Humans even the local demo needs to be able to send data there.

**Comment by KirstieJane** [comment]
Exxxxxxcellent - thank you @gedankenstuecke! I think the internet should be ok, but that's a great point to remember.

**Comment by GeorgiaHCA** [comment]
We should maybe also print out some posters?

**Comment by GeorgiaHCA** [comment]
Event was great! - made some good contacts :D Thanks for helping everyone!
