### ISSUE TITLE
Add technical guides to resources folder 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#491]
## Summary

We have a resources folder for people seeking support taking part in the project, with a sectoin for technical guides - but no guides in there! 

https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/Resources

## Details

* GitHub
* UX design
* Python
* Django

## Who can help

Anyone with skills in these areas with recommendations

**Comment by GeorgiaHCA** [comment]
Would you be able to add some resources to this folder @sowmya9507 or @anoura12?

**Comment by sowmya9507** [comment]
@GeorgiaHCA  sure on it! :D

**Comment by GeorgiaHCA** [comment]
Yay! Go @sowmya9507 ! Also a great first issue for people

**Comment by lottycoupat** [comment]
@sowmya9507 have made you the main assignee! Feel free to add anyone who helps :D

**Comment by lottycoupat** [comment]
@sowmya9507 I know we merged some stuff yesterday - but are you planning on adding more things? 😄
