### ISSUE TITLE
July 2021 Newsletter

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#530]
## Summary

The Newsletter for the month of July needs to drafted, reviewed and published. 

## Date Due by

23/07/21

## Details

* [ ] Draft 
* [ ] Review
* [ ] Publish

## Who can help

Anyone interested in review the newsletter please comment on this issue. 

Every month we do a spotlight contribution; if you would like to be the spotlight for next month's newsletter please comments on this issue. The questions covered are:

- Tell us a little about yourself...
- What are your favourite hobbies/things to do?
- What have you been working on for the AutSPACEs project?
- Give your best tips and tricks for contributing?

**Comment by GeorgiaHCA** [comment]
Heya @lottycoupat - I've reviewed the newsletter! This is a useful issue let's copy it for the next newsletter too?

**Comment by lottycoupat** [comment]
@GeorgiaHCA Yeah sounds good! Just wanted for Susanna to read over the July one with her spotlight and then can be sent off :D

**Comment by GeorgiaHCA** [comment]
Perfect!
