### ISSUE TITLE
Prepare for presentation at the Open Human Community call on September 7th

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#537]
## Summary

We have a slot at the Open Humans monthly community call on the 7th of September 2021. 

## Date Due by

7/09/21

## Suggestions for tasks that can fix this issue

* [ ] Plan the content we want to present
* [ ] Find volunteers to present
* [ ] Draft slides for presentation
* [ ] Review slides for presentation
* [ ] Present

## Who can help

Anyone who is interested in taking part in the presentation.

**Comment by skfantoni** [comment]
Always happy to present :)
