### ISSUE TITLE
Half year report for TPS on the AutSPACEs project

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#551]
## Summary

The AutSPACEs project will need to carry out a report to TPS on the project tasks and achievements in the past 6 months. 

## Date Due by

October

## Suggestions for tasks that can fix this issue

These are the following areas we need to answer/cover for the report:

* [x] Notable/substantive activity/outcomes in research progress	
* [x] Status of progress against goals/milestones, any blockers to progress
* [x] Conference/workshop talks presented (please name the event, dates – include link/s)
* [x] Papers submitted or published (include link/s)
* [x] Articles/blogs/press releases published (include link/s) 	
* [x] Software/code/tools/methods developed/released (include link/s)
* [x] New datasets created/accessed 	
* [x] External engagement, influence, impact (Academic/ industry/ government/ public/ international)
* [x] Funding: Further funding, leveraged funding/support, in-kind contributions	
* [ ] Patents (drafted/applied for/granted)
* [ ] Awards/recognition	

## Who can help

Anyone who has any ideas on the above categories, please comment them on this issue.

**Comment by BrainonSilicon** [comment]
RE: papers submited
- Georgia, Kirstie, & I worked on the LIBER chapter for Ethics and Citizen Science

**Comment by GeorgiaHCA** [comment]
This is ready for review now all, @KirstieJane: https://hackmd.io/T1w9qZHpQBqlpI9wujh1rw?both 

If anyone could double check the issue and pr count that would be amazing!!! I used this search syntax for issues and prs - Is:issue is created:2021-07-01..2021-09-30
Is:issue is closed:2021-07-01..2021-09-30
is:pr is created:2021-07-01..2021-09-30
is:pr is closed:2021-07-01..2021-09-30
Is:pr is merged:2021-07-01..2021-09-30

Hopefully that's right?

**Comment by GeorgiaHCA** [comment]
Update has been sent thanks everyone!
