### ISSUE TITLE
September newsletter

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#553]
## Summary

The September newsletter needs to be drafted and sent out before the 30th of September. 

A spotlight contributor also needs to be chosen. 

## Date Due by

30/09/21

## Suggestions for tasks that can fix this issue

* [ ] Draft
* [ ] Find a Spotlight Contributor
* [ ] Review
* [ ] Send out

## Who can help

Anyone who has an interest in Newsletter writing and communication. 

If someone would like to be the spotlight contributor for the newsletter, please comment on this issue and @lottycoupat will send over the questions that need to be answered for it.

**Comment by SuziQpid** [comment]
Done the spotlight reviewer bit already where's the box for proofreading to tick ?

**Comment by SuziQpid** [comment]
Oops realised what you really meant which is how do we find people to take over these tasks not only for this month but ongoing ? I definitely can't draft.

**Comment by GeorgiaHCA** [comment]
Hi @SuziQpid ! It's such a good question. I've been talking to Kirstie about it and reckon I will take over writing the monthly newsletters, while Soledad will be running the meet-up sessions and and @badgermind has agreed to keep up momentum with the dev sessions. In the long term we will have a new community manager who can work on the community aspects of the project, so we will just need to cover tasks for a few months.

**Comment by lottycoupat** [comment]
Hi @SuziQpid If you could read over the newsletter in the [PR here](https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/558/files) that would be great! I would like to get it out today, so if you don't have the time no worries!

@GeorgiaHCA could you review it also please 🙏

**Comment by SuziQpid** [comment]
I can't read it till 12. 30 . Will pass comments on to you by 1.

Hope that's ok

Sue.

**Comment by lottycoupat** [comment]
@SuziQpid That's awesome, thank you!

**Comment by SuziQpid** [comment]
Hi Lotty,

It all looks fine to me apart from the suggestion that you should change the query/ contact link to be someone else now that you’re leaving. There are two or three places, beginning, mid way and end of the newsletter where you have your email contact entered. 

I think it was agreed that Georgia would temporarily take over being the newsletter and collation of contacts for new collaborators/ contributors. So please take your email out and put hers in. 

I didn’t go through my spotlight piece. If there’s any blinding errors, they were mine when l submitted it.

Take care. See you on a screen somewhere. 

Suzanne lwai

Ps very general query ..does Alan Turing ever sponsor smart building solutions. eg a mobile concierge system that we want to put in our new civic campus in Hammersmith … money is running out and cabinet members say our business model isn’t strong enough. We simply want to make sure Autistic people, visually impaired and heavily pregnant women have a means of bring located, then assisted in emergency situations. Trying to avoid panic, unplanned births in toilets, and accidents in general.
