### ISSUE TITLE
Turing Visit Presentation Prep

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#56]
Here's a slide i've presented at a focus group: 

![image](https://user-images.githubusercontent.com/46889966/66475793-f8fa0780-ea8b-11e9-9672-098c080f2c89.png)

Adapt slide - along the bottom - logos (and minimise) - take question from James Lind Alliance - How could sensory processing in autism better be understood? - url to priority setting - collaborating with Autistica - and in 2017 ran priority setting exercise - read about here - and one of them was - our goal to use data science and citizen science to be able to answer this question at scale…

Visit to Turing health programme - one slide and talk for 3 minutes to present the citizen science project.

**Comment by KirstieJane** [comment]
Thank you so much for doing this presentation @GeorgiaHCA! Sorry I can't be there.

You only have 3 minutes so be sure to add in the research question to the slide and link to the priority setting page: https://www.autistica.org.uk/our-research/our-research/your-research-priorities.

The goal is to show off the Turing Health programme and so if you can also say that this project brings together academia, industry and the 3rd sector, and links between the Turing Health, Research Engineering and Public Policy (ethics) programmes that would be great. (We also need to connect better to the urban analytics programme! This is super relavent!)

* Here are the challenges for reference: https://www.turing.ac.uk/research/challenges
* Here are the https://www.turing.ac.uk/research/research-programmes

**Comment by GeorgiaHCA** [comment]
OS comments: 

Maybe add a suggestion box, so people viewing the presentation can add comments or extra questions
Have a guide, or a booklet, which explains the project - refer people to somewhere online. 
Like ore of an explanation of different terms - almost like subtitles participation and inclusion - a line or two to give an idea what that could mean, a specific example of what a person could be doing - (e.g. OS helped me draft presentation)
Liked whole speeach! :) (GA - thanks!)
Break down sensory processing in a way which is easier to interpret 
Short video - or clip - with image?

**Comment by GeorgiaHCA** [comment]
[CSPPresentationSlide.pptx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/3712139/CSPPresentationSlide.pptx)

In the end I didn't present this because the format was changed to a structured discussion, but uploading here in case useful for future events

**Comment by EllenDevereux** [comment]
This is nearly ready to close. Pull request needs reviewing by @GeorgiaHCA.
