### ISSUE TITLE
PS-SIG Presentation 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#562]
## Summary

The Turing's praticipatory science special interest group is holding workshops with members. Malvika and I have voluntered to present on planning community involvment showing the OLS open canvas, and AutSPACEs as an example of how it can be used. 

## Deadline

Nov 24th

## Details

Working on the slides here: https://docs.google.com/presentation/d/1N9IiRCDQnMKUhv6O6l-0rCy7nLnvREiLuWmiS5suLpA/edit#slide=id.gee8fa97325_0_0

**Comment by KirstieJane** [comment]
This looks great - I'm so glad that you were able to get this presented and discussed!

What's the goal for closing this issue? Capture the presentation somewhere in the repository (through a PR) so that we don't forget that you've done it?
