### ISSUE TITLE
October Newsletter

### ISSUE THREAD

**Issue by soledadli** [alan-turing-institute/AutisticaCitizenScience#563]
## Summary
The September newsletter needs to be drafted and sent out before the 30th of October 29th.

A spotlight contributor also needs to be chosen.

## Date Due by

29/10/21

## Suggestions for tasks that can fix this issue
- [ ] Draft
 - [ ] Find a Spotlight Contributor
 - [ ] Review
 - [ ] Send out

## Who can help
If someone would like to be the spotlight contributor for the newsletter, please comment on this issue and @GeorgiaHCA 
and @soledadli will send over the questions that need to be answered for it.

**Comment by BrainonSilicon** [comment]
Hi @soledadli 

Just wanted to check and see if we could close this issue as the Newsletter was sent out. (Great job by the way 🚀)
