### ISSUE TITLE
Labelling user stories

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#57]
Hey @SaimaButt

Thanks for doing the user stories on the OH demo repo (under issues):

https://github.com/alan-turing-institute/autistica-filemanagement-demo/issues

Do you think you could label them as user stories, so it's clear they are all part of the same group, and link to them from this repo?

😸

**Comment by SaimaButt** [comment]
Hi Georgia,

Apologies for the late response.
Of course I will get working on that and have it done by Monday.


Kind Regards,

Saima Butt
App Delivery Manager / Business Analyst
EMEIA DTS UK MCS SP CAP ATLDevOps

Fujitsu Services
Lovelace Road, Bracknell, Berkshire, RG12 8SN

Mobile: +44 (0) 7867 829567
Email: saima.butt@uk.fujitsu.com<mailto:saima.butt@uk.fujitsu.com>
Byte: byte@uk.fujitsu.com<mailto:byte@uk.fujitsu.com>
Web: http://uk.fujitsu.com<http://uk.fujitsu.com/>

**Comment by SaimaButt** [comment]
Hi Georgie

Are you able to get me permission to add labels to tickets and assig issues.

Kind Regards,

Saima Butt
App Delivery Manager / Business Analyst
EMEIA DTS UK MCS SP CAP ATLDevOps

Fujitsu Services
Lovelace Road, Bracknell, Berkshire, RG12 8SN

Mobile: +44 (0) 7867 829567
Email: saima.butt@uk.fujitsu.com<mailto:saima.butt@uk.fujitsu.com>
Byte: byte@uk.fujitsu.com<mailto:byte@uk.fujitsu.com>
Web: http://uk.fujitsu.com<http://uk.fujitsu.com/>

**Comment by KirstieJane** [comment]
I've just sent you an invite to have that access @SaimaButt.

I just want to double check that you know that when you send replies by email they're public, along with your email signature? You should be able to click the 3 dots (`...`) at the top of your comments in this issue to edit the text if you'd like?

**Comment by EllenDevereux** [comment]
@EllenDevereux @SaimaButt We will check this issue in my meeting with Saima later today.

**Comment by EllenDevereux** [comment]
Ellen has labelled all user stories during co-working session with Georgia. This issue was included in that method.
