### ISSUE TITLE
Link to other organisations 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#590]
## Summary

AutSPACEs cannot provide certain forms of support, so we need to find appropriate organisations to refer people to whose nees cannot be met by the platform. 

## How to help

If you have aany suggestons of either a)user needs which might need external support b)organisations or links to add

**Comment by GeorgiaHCA** [comment]
We should open this for wider community discussion

**Comment by GeorgiaHCA** [comment]
[Autistica](https://www.autistica.org.uk/)
[National Autism Society](https://www.autism.org.uk/)
[Samaritans](https://www.samaritans.org/)
[Mind](https://www.mind.org.uk/)
[Scope](https://www.scope.org.uk/)
[MENCAP](https://www.mencap.org.uk/)

**Comment by skfantoni** [comment]
Never saw this and wrote my own issue #600 lol
