### ISSUE TITLE
Arranging follow-up meeting: Fujitsu/Alan Turing

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#60]
- [ ] Internal Fuijtsu meeting to discuss timeframes/setup team
- [x] Imogen to organise with Georgia Turing/Fujitsu meeting (KW on strike 25th Nov - 5th Dec)
  * Date agreed: 13 January from 10am to 3pm
  * Need location
- [x] Meeting agenda agreed
- [ ] Order lunch from Bunego - lets go for all vegetarian this time and get some desserts :yum:

**Comment by KirstieJane** [comment]
One of the things I'm keen to add to the agenda and make sure we're clear about is the _process_ for working through the user stories.

I think the actual prioritising needs to include insight group members and/or autistic community members, but I'd like to make sure that we're clear on what we'd be asking of them before those sessions! There's some work to do explaining to me how the user stories and agile processes can fit into a participatory and open design framework 😸

**Comment by GeorgiaHCA** [comment]
On Monday 13th January some of the Fujitsu team are visiting @KirstieJane & @GeorgiaHCA at the Turing Institute for our second co-working day.

This issue is to capture the agenda and goals of the day, all comments welcome! Any other suggestions for the warm-up session also great - this is just an idea. 

### Agenda

*Proposed - comment below with suggestions to change the plan*

| Time | Agenda item | 
| ----- | --------------- |
| 10:00 | Warm up session: Q & A Catch | 
| 10:45 | Mapping who is involved |
| 11:15 | Biobreak ☕️ |
| 11:30 | User stories: determining process| 
| 12:30 | Lunch 😋 |
| 13:30 | Open source: facilitating contributors | 
| 14:15 | Biobreak ☕️ |
| 14:30 | Discussion: Roadmap and next steps | 
| 15:00 | Close | 

#### Warm up Session

In this session we share questions and expertise. 

* Part 1: each person asks the person to their right a question they don’t know the answer to. Could be serious or silly. The next person has to recite (or summarise) the question and add their own answer. Each new person recites the question, the previous answers, and adds a contribution of their own. 
* Part 2: each person thinks of a question they don’t know the answer to (but which they think it would be useful to have an answer to) and throws a ball into the air. Whoever catches the ball (or we could do this in a ring, so everyone gets a chance), either answers the question, or repeats the question (if they don’t know the answer), and throws it again. The next person can either add more to the answer, correct the answer or ask a new question. The aim is not to let the ball drop.
* Part 3:  the two combined – everyone has to try to remember the comments and the whole group tries not to drop the ball.

#### Mapping who is involved

We map out who we think it is important to be involved in the development process, and think about the communication flow between them

#### User stories: Determining process

We clarify the prioritisation and assessment process for the backlog

#### Open Source: Facilitating contributions

A structured discussion on how contributions from community members can fit into the process.

#### Discussion: Roadmap and next steps

Closing out the sprint with a reflection on the day and agreeing next steps.

### Logistics

* Turingery meeting room
* Arrive through main British Library entrance (after doors open at 9:30am)
* Lunch ordered by facilities team

**Comment by GeorgiaHCA** [comment]
Thanks Everyone!

This was a great meeting - I'm so excited about the working process we're getting going with, and seeing how Open source and Agile methods can be knitted together ✨😸
