### ISSUE TITLE
Plan user testing for front end

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#61]
"As a contributor I want to gather feedback from members of the autistic community so that the platform ireflects them" 

"As an autistic person or relative or carer of an autistic person I want to give my feedback so that the platform reflects me" 

"As a researcher I want autistic people and their relatives and carers to give their feedback so they are incentivised to participate in the study and have a good experience of interacting, and so that I can collect the best data which can have the most beneficial impacts" 

- [x] Find/allocate UX designer from Fujitsu to project (Andrew H)
- [x] Liaise with Autistica to recruit Insight Group participants as testers (Georgia A)
- [x] Arrange/run sessions - build into sprints

**Comment by EllenDevereux** [comment]
This has been built into the process documentation.
https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/agile-opensource-workflow.md
