### ISSUE TITLE
Create session for MozFest

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#613]
## Summary

“Co-creating and citizen science with AutSPACEs” - online discussion session 
2022-03-07 at 14:45 Central European Time (UTC+1)

## Date Due by

7th March 2022 at 14:45 Central European Time (UTC+1)

## Details

- [x] invite co-presenters
- [x] plan session
- [x] Create slides and resources
- [x] practice run
- [x] run session
- [x] collect feedback

**Comment by GeorgiaHCA** [comment]
Plan in this [HackMD](https://hackmd.io/fSJdeZiARF2LVUvdLh9ZPQ)

**Comment by GeorgiaHCA** [comment]
Storyboard in [Miro](https://miro.com/app/board/uXjVOM-p0bI=/)

**Comment by GeorgiaHCA** [comment]
Hiya @BrainonSilicon - I've been working on the Miro Board here: and the presentation here: https://docs.google.com/presentation/d/1s7YGnTSaty09i0GmQB6hTfTWAr6xZ5SnL5Q2SCZyRZI/edit#slide=id.g116e6efa651_0_61 and the Miro board here: https://miro.com/app/board/uXjVOKJ3Rkk=/ both WIP but feel free to add and edit :)

**Comment by GeorgiaHCA** [comment]
I thought instead of having separate boards we could have separate coloured stickynotes for private and public comments

**Comment by GeorgiaHCA** [comment]
<img width="904" alt="Screenshot 2022-02-23 at 21 11 51" src="https://user-images.githubusercontent.com/46889966/155410040-ca00bf26-104f-4574-812a-4a2bc93326f2.png">

**Comment by BrainonSilicon** [comment]
> I thought instead of having separate boards we could have separate coloured stickynotes for private and public comments. The icebreakers as people arrive can also then give people a chance to get to grips with it before the breakouts. What do you think?

I like the colour differentiation. We may need more space in each section if there are lots of participants. How would you feel about creating vertical space (i.e. columns) so that things could be added endlessless to each question (instead of just within a box) 
- was thinking ^ based on the struggle we had with the boxes today and having to resize post-its a lot. 

I love the text box you've put beside the board - it makes it super clear! 🚀

**Comment by GeorgiaHCA** [comment]
Yep, that works!

**Comment by GeorgiaHCA** [comment]
Updated link for slides: https://docs.google.com/presentation/d/14Zbwv4cAZQ_0riKCn205kRkompRFkWUDGvpSKcIigRY/edit#slide=id.g117134208ab_0_826

**Comment by BrainonSilicon** [comment]
Gave MozFest presentation today!
