### ISSUE TITLE
🐛 BUG: Spelling and Grammar fixes needed in Personas documents

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/AutisticaCitizenScience#641]
## Summary
Welcome! This is a great issue to get started on. 

If you are new to the AutSPACEs project, please familiarise yourself with our central [README](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/README.md) document to learn about the project, and then read through our [Guidelines](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/.github/CONTRIBUTING.md) on how to contribute to the project.

## Details
There are a few spelling and grammar issues in the Personas document. You can choose any of the below files to review and edit by submitting a Pull Request. Please "tick" the corresponding box below to let the community know which one you are working on and when you are done. 

- [ ] Read through the [Kendall](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/platform-designs/design-research/Personas/Kendall.md) persona document, and fix the grammar errors to make the document read easier. 

## Who can help

Anyone can help! This would be a great first issue to get started with!!

**Comment by akebu6** [comment]
I have made some changes to the readme of Kendall's persona and awaiting feedback on what has to be changed again
