### ISSUE TITLE
Create a slide deck and record a presentation for the Autistica Fest 2022

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#657]
## Summary

Slides, along with abstract and info, are here: https://docs.google.com/presentation/d/14jfp8l6ng7eiWD-KsnGy-pow-9W0z3PgsJ_8a6W4bjo/edit?usp=sharing 

## Date Due by

Return to Autistica by 30th May

**Comment by GeorgiaHCA** [comment]
@JamesSCTJ and @skfantoni here's the issue relating to the Autistica festival if you'd like to be involved. The info is at the beginning of the slide deck 😸

**Comment by BrainonSilicon** [comment]
Hey team! 

Based off the abstract, we were thinking that the presentation could be layed out as a comparison between the "traditional" research cycle vs. the way AutSPACEs has been designed. 

How I was imagining it was something like this:

> Explain traditional research cycle
> Differentiate this from autspaces
> - Q came from the community
> - Research process co-designed in scoping sessions (including how we would process data)
> - Eg. needs -> user needs -> design 
> - Eg. Needs -> moderation 
> - Data gathering - citizen science (co-created open citizen science tool) “decisions not passive data points” 
> - Citizen Science not participants
> - Recruitment via. Autistica’s Insight Group 
> - Data analysis - open, some autonomy (people can revise own data)
> - Implementation
> - (Socially embedded - institutional structures)
> - Open Science 
> - Github - even this presentation is on github

**Comment by BrainonSilicon** [comment]
There's a good image of the research cycle from The Turing Way (courtesy of Scriberia). I'll post it below
![ResearchCycle](https://user-images.githubusercontent.com/42813259/170970531-ba9d3853-49d8-4677-a506-e1cda370089e.jpg)
.

**Comment by GeorgiaHCA** [comment]
Congrats @BrainonSilicon and @skfantoni  🎉 🎉
