### ISSUE TITLE
Link appears to be broken

### ISSUE THREAD

**Issue by arronlacey** [alan-turing-institute/AutisticaCitizenScience#666]
## Summary

The `creation-summary-documents.md` referenced [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/community-recommendations/moderation-co-creation) appears to be broken (or rather doesn't exist).

**Comment by GeorgiaHCA** [comment]
Good spot @arronlacey ! 👍 I'll fix this

**Comment by BrainonSilicon** [comment]
Hiya team! 

I found the document located in `community-recommendations/focus-groups/creation-summary-documents.md`. 

The permalink is [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/3aeff0597f0c129e910ae2ea39aeb93382b7242b/community-recommendations/focus-groups/creation-summary-documents.md) 

@GeorgiaHCA - if you edit the correct link back in, I'm happy to review the PR.

**Comment by GeorgiaHCA** [comment]
🎉 thanks Sophia!!

**Comment by GeorgiaHCA** [comment]
I made a commit to add the correct version of the doc to the folder so the link should work now

**Comment by BrainonSilicon** [comment]
Awesome! Looks like we can close out this issue. Great work team! 🚀
