### ISSUE TITLE
Fill in Researchfish

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#67]
_Deadline 22nd January_

"As a research organisation I want to be able to track the projects I fund so that I can see how they are progressing"

"As a researcher I want to track my research and share it with funders to ensure expectations are aligned and to make sure our work is transparent."

Track impact assessment: https://www.researchfish.net/

**Comment by EllenDevereux** [comment]
Close this issue
