### ISSUE TITLE
AIM RSF - AutSPACEs Presentation

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/AutisticaCitizenScience#677]
## Summary
The AutSPACEs team is giving a presentation to the AIM RSF.

## Date Due by
September 26th

## Details
- [WIP Presentation](https://docs.google.com/presentation/d/1eSmeyx-zsbEEEaj5-xj28uEpgBFtPTFY7P2sXRIivu8/edit?usp=sharing)

**Comment by BrainonSilicon** [comment]
* [Jamboard](https://jamboard.google.com/d/10vHNC4lAi3DH6IwHTWBd-6EBjftP-fxLwph9qnc7Ne4/edit?usp=sharing) for planning

**Comment by GeorgiaHCA** [comment]
Slides to reuse? 
[Citizen Science and Community](https://docs.google.com/presentation/d/1OcKq_1PewFt4XbiARphWE5OUcrIcggBYSQ1eRVDWvH8/edit#slide=id.g13363cbb8e4_0_5)

**Comment by BrainonSilicon** [comment]
Previous presentations to crib from 

* [Autistica Festival](https://docs.google.com/presentation/d/14jfp8l6ng7eiWD-KsnGy-pow-9W0z3PgsJ_8a6W4bjo/edit#slide=id.g12e531ed5ac_1_1294) good for the remixed research cycle

**Comment by BrainonSilicon** [comment]
### WIP Presentation 
- https://docs.google.com/presentation/d/1eSmeyx-zsbEEEaj5-xj28uEpgBFtPTFY7P2sXRIivu8/edit?usp=sharing

**Comment by GeorgiaHCA** [comment]
Slides have been uploaded to Zenodo and linked to from the repo here: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-communications/presentations/README.md 

Thanks @BrainonSilicon !!! Was fab to present with you. Closing this issue now.
