### ISSUE TITLE
Create and Send January Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#68]
"As a collaborator I want to receive regular updates so that I can easily see how the project is progressing and how my contributions are being used"

"As a researcher I want to share information with collaborators on the project's progress so that I can build a community and get feedback on my work" 

- [x] Interview OS and get picture
- [x] Write
- [ ] Review
- [ ] Send to Mailing List

**Comment by EllenDevereux** [comment]
- [ ] waiting for focus group summaries

**Comment by EllenDevereux** [comment]
Write new newsletter
