### ISSUE TITLE
Write guidelines for reading assessing focus groups

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#75]
- [x] Write draft of guidelines
- [x]  Get feedback on clarity and usability
- [x] Redraft based on feedback
- [x] Review redraft
- [x] Circulate along with summaries to participants
- [x] Add as documentation to the repo in the form of a pull request

**Comment by GeorgiaHCA** [comment]
[Guidance.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4087051/Guidance.docx)

First draft of guidelines

**Comment by GeorgiaHCA** [comment]
[GuidanceJSComments.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4087066/GuidanceJSComments.docx)

Suggestions from changes from JS - Thank you so much for helping! These comments are brilliant and I'll action them now 👍

**Comment by GeorgiaHCA** [comment]
[Uploading GuidanceRedraft.docx…]()

Here's a redraft incorporating JS's suggestions

**Comment by GeorgiaHCA** [comment]
[GuidanceRedraft.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4087199/GuidanceRedraft.docx)

Here's a redraft based on JS's comments

**Comment by JamesSCTJ** [comment]
Thanx

**Comment by GeorgiaHCA** [comment]
[Guildeines3.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4114557/Guildeines3.docx) Third version of guidelines with diagrams :)

**Comment by GeorgiaHCA** [comment]
Attributions for icons in guidelines: (https://thenounproject.com)  

Conversation by Pause08 from the Noun Project
transcript by 8TIES® from the Noun Project
Document by Jamison Wieser from the Noun Project
Eye by kiddo from the Noun Project 
online by priyanka from the Noun Project
to do list by Ben Davis from the Noun Project

**Comment by GeorgiaHCA** [comment]
Great Work Kirstie and James! Thanks for all your help 😸
