### ISSUE TITLE
Open Source/ Agile Workflow - Decide on Process

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#77]
[OpenSourceAgile.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4116831/OpenSourceAgile.docx)

Hi everyone, here's a potential version of the workflow combining agile, open source, and participatory science. Still just a fairly simple version. Would love your input!

**Comment by KirstieJane** [comment]
Just reviewing this now @GeorgiaHCA - I think the figure needs some numbers next to it - its hard to know where to start....
