### ISSUE TITLE
Give talk at Turing Data Science for Mental Health special interest group

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#80]
@GeorgiaHCA is giving a talk at the 

* Slide 1: all good
* Slide 2: play the video 
* Slide 3: spend some time on this slide - have some of the stats available from the uk research review in a hidden slide in case you get questions about these points
* Slides 5, 6, 7: (I made these so obviously I like them :laughing:)
* Slide 8: this is great - the audience will know what github is but won't necessarily have used it - maybe add another slide with some images of conversations on issues and pull requests
  * Add in example of focus groups and getting feedback on them!
  * Maybe have a hidden slide on research that shows that participants don't read consent forms and don't know what is happening with their data 😬 
* Slide 11: Don't forget to add collaborators
* Slide 12: looks good to me 😄 

There's a risk that this group are going to ask where the hypothesis is: what model are we testing. Think about a response that is about the _processes_ and _practices_ of developing software engineering, demonstrating how we embed ethics into the tools and systems we build, and focusing on *who* gets to direct research questions and for what purpose.

Aim for 20 minutes of talking and 10 mins for questions.

**Comment by GeorgiaHCA** [comment]
Thanks so much for your help and mentoring Kirstie! :)

**Comment by KirstieJane** [comment]
The talk was great @GeorgiaHCA! I've reopened the issue because we didn't capture your slides in the repository anywhere. Can you have a think about where we could put it? And maybe add the videos and slides from other talks we've given too?

**Comment by EllenDevereux** [comment]
@GeorgiaHCA add slides to the file made in previous issue.

**Comment by GeorgiaHCA** [comment]
Files now uploaded in presentations folder
