### ISSUE TITLE
Gather platform requirements

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#84]
- [x] Send round summaries to participants and publish on GitHub
- [x] Turn summaries from focus groups into user stories
- [x] Redact personally identifying information from Google Forms Surveys and turn into user stories 
- [x] Explore Open Humans backend and understand data flow and itegration 
- [ ] Turn these into issues/requirements 
- [x] Onboard Ellen and Emilia 
- [ ] Consult with Autistica on their information
- [ ] Gather requirements from Alan Turing from researcher perspective 
- [x] Go through GitHub issues

**Comment by fjThomasStanley** [comment]
A google sheets has been created to begin the process of recording Focus Group session comments into formalised User Stories. Link to this doc will be shared once Alan Turing have approved public access to Focus Group session content can be shared publicly.

**Comment by fjThomasStanley** [comment]
In order to gather/consult on requirements from Autistica, Fujitsu are suggesting that we can setup a Business Analysis meeting/interview with them. Fujitsu suggests this as a means to gather relevant user story information that does not require access to the, as current, restricted and confidential set of information gathered from the Autistic Community focus group sessions as held in Sep/Oct 2019. Fujitsu would like any information gathered directly from Autistica, to be immediately shareable within the Fujitsu team so that work to generate User Stories can be conducted straight after the suggested Business Analysis meeting with Autistica.

**Comment by KirstieJane** [comment]
@fjThomasStanley - this all sounds great. I don't think there's any reason for the comments that come from Autistica to be confidential in anyway - so if they can be uploaded via the Google form or in a GitHub issue that would be great!

One point of clarification - your comment above (https://github.com/alan-turing-institute/AutisticaCitizenScience/issues/84#issuecomment-580819620) seems to imply that the feedback from Autistica will be the same as the insights from the focus groups. I don't think that's going to be the case - in fact I'm pretty sure Autistica are going to say that listening to members of the community is the best way to develop the platform requirements!

That's not to say at all that you can't chat with them - learning from the team at Autistica's experience is a very high priority! But there was something about your phrasing that made me want to clarify.

**Comment by fjThomasStanley** [comment]
Further to @KirstieJane question about feedback from Autistica being the same as that from the focus groups: I would like to clarify that the Focus Group Session content cannot and will not be used for requirements at this stage in the project lifecycle. The aim of speaking to Autistica is to create a new set of content that is totally separate from the focus group content that can be worked with freely by Fujitsu.

**Comment by EllenDevereux** [comment]
These need to break up into separate issues 
1. Open Humans - Georgia and Thomas - Georgia will link Thomas to Bastian, Thomas will look through business requirements document as background and explore Open Humans backend - capture knowledge, and document questions - Labels - Fujitsu, High, Platform Delivery
2. Turn Summaries into User Stories - Georgia / Autistica Team / Thomas - Labels - Autistica, Fujitsu, Turing High, Data Management
3. Document onboard Emilia and Ellen - Turing, Fujitsu, High, Bulding a healthy community, medium
4. Document consultation with Autistica - Fujitsu, Autistica, Platform Delivery, medium
5. Organise issues and write new issues - Fujitsu, Autistica, Turing, high, Building a healthy community

**Comment by EllenDevereux** [comment]
@fjThomasStanley can you please confirm what of these have been done and let us know what else needs doing.

**Comment by GeorgiaHCA** [comment]
This is already in progress this issue is outdated so closing - we do still need to consult with more folks who are autism researchers about what will be useful
