### ISSUE TITLE
Onboarding Deck for upload

### ISSUE THREAD

**Issue by EllenDevereux** [alan-turing-institute/AutisticaCitizenScience#87]
[Project Onboarding.pptx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4152626/Project.Onboarding.pptx)
Please can you add this to your comms file. @GeorgiaHCA

**Comment by EllenDevereux** [comment]
- [ ] Review by Fujitsu team
Labels - Fujitsu, high
Assign - Emilia 
Milestone - Building a Healthy Community

**Comment by EllenDevereux** [comment]
This has been approved by FJ team. Can it be uploaded and this issue closed? @GeorgiaHCA

**Comment by EllenDevereux** [comment]
I now know how to do this, so I will.

**Comment by GeorgiaHCA** [comment]
Hiya @Ellen - I've now uploaded this and created a separate fujitsu comms file here: https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/project-communications/fujitsu
