### ISSUE TITLE
Create Kanban style PM page with GitHub projects

### ISSUE THREAD

**Issue by JamesSCTJ** [alan-turing-institute/AutisticaCitizenScience#91]
I'm organising the issues into a Kanban style projects board to ensure that the workflows are presented as intuitively as possible. Anyone from the Turing, Fujitsu or the wider community is welcome to comment or give feedback on what would be useful.

**Comment by GeorgiaHCA** [comment]
Thanks James! This is a great thing to be doing. Also looking forward to getting your first pull request. You are a STAR!

**Comment by EllenDevereux** [comment]
Assign Saima to collaborate with James
Milestone - Building a Healthy Community
Label - High

**Comment by KirstieJane** [comment]
This is great - we can capture some documentation (maybe some screenshots?) for future contributors that would be great! Pointing out how issues move across the different columns according to either automated or manual processes.

**Comment by JamesSCTJ** [comment]
Hi Saima, great to be working with you! Shall we catch-up on this shortly?

**Comment by EllenDevereux** [comment]
@SaimaButt and I are doing this this afternoon. @JamesSCTJ would you like a chat with me after mine and Saima's meeting so I can explain how we plan on using the board? We'd love your participation.

**Comment by JamesSCTJ** [comment]
Hey! I'm happy to talk to you about this!

James

**Comment by EllenDevereux** [comment]
James, my email address is ellen.devereux@fujitsu.com please drop me an email and I'll set up a meeting (skype call) with you to discuss the changes we've made and how you may be able to assist going forward. ( @GeorgiaHCA  is this ok?)
