### ISSUE TITLE
Write requirements document to define Fujitsu's deliverables

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#92]
We need a 1 page description of a very high level set of requirements for review by the Fujitsu team so they can align themselves and allocate tasks appropriately.

It should probably contain:

- [x] A description of where data will flow from the website 
- [x] Interactive wireframes for user research and feedback
- [x] User journeys 
- [x] Open source implementation of the design
- [x] Technical specifications for maintaining the website after the Fujitsu project has ended
- [x] Documentation on how decisions were made (eg: infrastructure choices, programming language / framework choice, design choices)
- [x] Public videos at the end of each sprint and an accompanying CHANGELOG cataloguing all the issues that were closed / opened / progressed on (@KirstieJane is going to write up the details of this!)
- [x] Planning, undertaking and reporting on monthly user experience research sessions
- [x] Commitment to project values

---

Updates:

Pull request open at #96 

- [x] Fuijtsu team to review and make changes as needed
- [ ] Kirstie and Georgia to confirm and merge

**Comment by KirstieJane** [comment]
I'm going to work on the "public videos at the end of each sprint" bullet point! 📹 🎥 🌟

**Comment by GeorgiaHCA** [comment]
Created a markdown for review of a proposed requirements doc :) 

Thanks for reviewing and editing Kirstie!!

**Comment by GeorgiaHCA** [comment]
https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/96 - link to pull request

**Comment by KirstieJane** [comment]
Reviewing now! Thanks @GeorgiaHCA 🌟

**Comment by EllenDevereux** [comment]
- [ ] Add checklist point to top issue for Fuijtsu team to review and make changes
- [ ] Kirstie and Georgia to confirm
