### ISSUE TITLE
Make sure all Fujitsu team members have GitHub accounts and are named as collaborators on this repository

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#98]
This is to ensure that everyone can manage issues on the GitHub repository

- [x] @fjThomasStanley
- [x] @SaimaButt 
- [x] @EllenDevereux 
- [x] @aharding15 
- [x] Emilia
- [x] Chris
- [ ] Craig

Actions:
* Sign up to GitHub
* Comment here with your username 
* @GeorgiaHCA to give team members write access to the repository

**Comment by EllenDevereux** [comment]
@driscolle is Craig needed on GitHub?

**Comment by driscolle** [comment]
Hi, I don’t believe so.

**Comment by EllenDevereux** [comment]
Since Craig Hall is not contributing directly to this project and the FJ developers will only be contributing to the FJ branch. All members of Fujitsu team requiring contributing access have accounts and access to the repo now.
