### ISSUE TITLE
Project planning visibility

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutisticaCitizenScience#99]
### I would like to...

be able to have visibility on project planning

### So that....

I can understand what the project can offer

### Acceptance criteria

- [ ] users have information about future plans or end goals of the project
- [ ] users can see who is involved with the project and what tasks everyone is working on
- [ ] users can record the time spent on project and information used for project

### Source of user story

This was a contribution from autistic person via the Google form.
The acceptance criteria was developed by @fjThomasStanley.

---

## Notes

* Associated pull request: 
* Current status:

---

**Comment by EllenDevereux** [comment]
We have created documentation and a project board which effectively demonstrates how this project is being run.
